### ISSUE TITLE
Windows 10 IE not Edge not woking 

### ISSUE THREAD

**Issue by WeBBLiu** [videojs/videojs-contrib-hls#1011]
Description
win10 IE video.js play m3u8 not woking , but chrome edge fine.

Sources
`<video id='myvideo'  controls preload='auto' class='video-js vjs-default-skin vjs-16-9 vjs-big-play-centered'  >`
 `<source src='http://vod.streamingfast.net/hls-vod/dvr/ch1.20170215_0200.m3u8' 
type='application/x-mpegURL'></video>`

videojs-contrib-hls version
v5.2.1  

videojs version
5.17.0

Browsers
Win10 
IE not working
Edge working
Chrome working

Platforms
Win10 

Other Plugins
none.

Other JavaScript
Jquery

**Comment by gkatsev** [comment]
Can you please fill out the [issue template](https://github.com/videojs/videojs-contrib-hls/blob/master/.github/ISSUE_TEMPLATE.md)? Specifically, the sections around which versions of contrib-hls, video.js, and browser and OS.
A reduced test case would be appreciated as well.
Thanks.

**Comment by forbesjo** [comment]
This may be related to this known issue https://github.com/videojs/videojs-contrib-hls#ie11

**Comment by alibrightman** [comment]
Windows 7 + IE 11 doesn't work either.
videojs-contrib-hls 5.2.1
Video.js 5.16.0

Test using [http://videojs.github.io/videojs-contrib-hls/](url)
Or [http://jsbin.com/vokipos/8/edit?html,output](url)
Video is expected to play, but doesn't.

Console errors:

`VIDEOJS: WARN: Failed to create SourceBuffers TypeError: Object doesn't support property or method 'vjs_appendChunkReady'`

(the debugger breaks at https://unpkg.com/videojs-contrib-hls/dist/videojs-contrib-hls.js Line 9398)

`VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. `

**Comment by gesinger** [comment]
@alibrightman , that looks like it is due to https://github.com/videojs/videojs-contrib-hls#ie11

**Comment by elhampour** [comment]
i dont have any error in ie 11 or below, but my videos wont play, maybe i have to use different coding for ts files or some thing else.

What should we do for this problem ?

**Comment by forbesjo** [comment]
@gesinger I think we should update the known issue note with something like 
```js
if ((/Trident\/7.0/i).test(USER_AGENT) && (/rv:11.0/).test(USER_AGENT)) 
  videojs.options.hls.mode =  'flash';
```

**Comment by mjneil** [comment]
@forbesjo I think we should raise an issue with `video.js` to set `videojs.browser.IE_VERSION = 11` when those user agent tests pass

**Comment by forbesjo** [comment]
`videojs.browser.IE_VERSION` can be used to detect IE11, in the future we'll be making this override easier.
