### ISSUE TITLE
VideoJS not playing high bitrate HLS video

### ISSUE THREAD

**Issue by arshanawais** [videojs/videojs-contrib-hls#1022]
I am trying to play an m3u8 file served by Wowza steaming engine at following address:

http://54.218.7.156:1935/vod/mp4:sample360.mp4/playlist.m3u8

The video has a high bitrate i.e. 13 mb/s. When I try to play it in VideoJS, network tab of the browser shows that the player keeps downloading the .ts file chunks again and again at regular intervals but never plays the file. I have tried this in Chrome & Firefox.

Same issue occurs with live stream instead of VOD. But in that case, instead of .ts file chunks, the m3u8 file keeps downloading again and again.

Low bitrate videos are working well in both live and VOD.

**Comment by mjneil** [comment]
This looks to be a bug. If the last rendition available in the playlist is playing, requests shouldn't timeout, but these requests are. It looks like the check for last rendition is only called on mediachange events, which should also happen for the initial rendition

**Comment by vpowers** [comment]
I've tested this fix with PR https://github.com/videojs/videojs-contrib-hls/pull/1006 and playback is working as expected.  Test was done with a long running live HLS stream using Wowza.  I can't confirm in the master branch (after merge) since playback of HLS is not longer working.  Possibly related https://github.com/videojs/videojs-contrib-hls/issues/1022.

**Comment by mjneil** [comment]
This should be fixed by #1032
