### ISSUE TITLE
Audio Skips Ahead With Some Videos, Not Others

### ISSUE THREAD

**Issue by belling** [videojs/videojs-contrib-hls#1036]
## Description

- Audio skips ahead, rapidly getting out of sync
- Observed in Chrome and Firefox, not tested in other browsers
- Affected videos work as expected in VLC
- Observed on tests using full length 60fps "Big Buck Bunny" video as source, at all bitrates generated
- NOT observed on tests with 44 second 1080p video taken directly out of DSLR

## Sources
Here are a few sample segments + playlist:
https://drive.google.com/drive/folders/0B3J2BegImS8ac3A5LVU2NmVZQlk?usp=sharing

## Steps to reproduce

1. Set playlist as video source 
2. Begin playing video
3. Note that before first segment is played, audio has skipped ahead to audio from later segments

### Expected

Expected audio to remain in sync

### Error output

None observed

### videojs-contrib-hls version

videojs-contrib-hls v5.2.1

### videojs version

Observed in:

Video.js 6.0.0-RC.2
AND
Video.js 5.16.0

### Browsers

* Chrome latest
* Firefox latest

Others not tested

### Platforms

* OSX 10.12.3

### Other Plugins

* None

### Other JavaScript

* Standard Zurb Foundation framework w/Jquery (although I'm only writing native functions). Not much custom JS going on.

**Comment by gesinger** [comment]
Hey @belling , thanks for reporting. I confirmed the issue you were seeing. It looks like in the example you posted, the TS files have two audio tracks per segment (one for stereo and one for 5.1). We don't currently support having two audio tracks in one TS file, as it isn't too common (since it uses excess bandwidth to pass both). However, we do support alternate audio tracks, which separates the audio from the video, meaning the player only needs to download the relevant audio file for the user's selection (or whatever is defaulted). We recommend using that instead.

If you are still experiencing issues with only one audio track in the stream (or none if using demuxed audio/video as part of alternate audio tracks), please let us know. Thanks again.

**Comment by belling** [comment]
Ah, thanks for looking into it. I was just using that source video because it was handy and couldn't figure it out.
