### ISSUE TITLE
Android Chrome, Chrome windows,Mac Safari vjs-seeking called on start of replayed video 

### ISSUE THREAD

**Issue by naveen2245** [videojs/videojs-contrib-hls#1045]
Seek function is called when the replay button is clicked on  videojs video in Android chrome,Chrome windows,Mac Safari without reloading the video . 

Please confirm whether this a videojs behaviour or is it specific to these browser ?

**Comment by gesinger** [comment]
Hey @naveen2245 , when someone hits the play button, if the video has ended, we seek back to the beginning of the video to restart: https://github.com/videojs/videojs-contrib-hls/blob/1fceb3e8932bd5b88acaa2e38d284441b9fbbb6a/src/master-playlist-controller.js#L925

This should be the case for at least any browser that doesn't support HLS natively (e.g., Safari), since it'll run through that code.

I'm going to close this issue for now as answered, but if you are experiencing any other behavior (for instance, the video not restarting or different behavior per browser), please re-open and let us know what you're seeing. Thanks!
