### ISSUE TITLE
 Difference between videojs-contrib-hls and videojs-contrib-hls-s1

### ISSUE THREAD

**Issue by chienming** [videojs/videojs-contrib-hls#1048]
Please allow me to ask a simple question :)

The Plugins and Skins page at http://videojs.com/plugins/ lists two HLS plugins

- videojs-contrib-hls (https://npmjs.org/package/videojs-contrib-hls)
Play back HLS with video.js, even where it's not natively supported

- videojs-contrib-hls-**s1** (https://npmjs.org/package/videojs-contrib-hls-s1)
Play back HLS with video.js, even where it's not natively supported

Both plugins require videojs-contrib-hls downloaded from https://github.com/videojs/videojs-contrib-hls/releases 

The latest version of videojs-contrib-hls is 5.3.3 while videojs-contrib-hls-**s1** has version 1.3.9.

What is the difference between the two plugins? Is videojs-contrib-hls-s1 the simplified version of videojs-contrib-hls? But they use the same videojs-contrib-hls file.

**Comment by mjneil** [comment]
videojs-contrib-hls-s1 appears to be an old fork of this project that someone published to npm. It is very outdated (over a year since its last update) and is not maintained by the videojs organization. I recommend using [videojs-contrib-hls](https://npmjs.org/package/videojs-contrib-hls) and not the s1 package

**Comment by gkatsev** [comment]
I wonder if we should get the s1 projects unpublished; thoughts @nickygerritsen?
