### ISSUE TITLE
Deploying videojs-contrib-hls to heroku

### ISSUE THREAD

**Issue by cjdeleon62** [videojs/videojs-contrib-hls#1069]
I am trying to an application to heroku that uses videojs-contrib-hls and I am getting an Uncaught SyntaxError: Unexpected token {. Has this happened to anyone before?

**Comment by gesinger** [comment]
Hey @cjdeleon62 , it sounds like there might be something wrong with how you're packaging your application together. Would you be able to provide more details as to how you're building your application and making use of videojs-contrib-hls? Thanks.

**Comment by cjdeleon62** [comment]
@gesinger I am building my application on Node.js and I am trying to use video-contrib-hls and video.js  with React.js. I I am using webpack to bundle the application and I think that is where it goes wrong. I saw on another forum that people resolved the issue of importing video-contrib-hls by doing the following:

webpack.prod.config.js
  resolve: {
      extensions: ['', '.js', '.jsx'],
      alias: {
          webworkify: "webworkify-webpack-dropin"
      }
    },

this was added to import video-contrib-hls into my application

and this is the react component I import video-contrib-hls into along with video.js in order to get the player running:
import React, { Component } from 'react';
import videojs from 'video.js';
import 'videojs-contrib-hls';

class Player extends Component {

  constructor(props) {
    super(props);
  }

  componentDidMount() {
    const options = {
        hls: {
            withCredentials: true
        }
    };

    this.player = videojs("video-player", options).ready(function(){
      console.log("i am ready");
    });

    this.player.src({src: 'http://184.72.239.149/vod/smil:BigBuckBunny.smil/playlist.m3u8', type: 'application/x-mpegURL'});
    setTimeout(() => {this.player.play()}, 1000);

  }

  componentWillUnmount() {
    this.player.dispose();
  }

  render() {
    return(
      <div style={{height:"100%", width:"100%"}}>
        <video id="video-player" style={{width:'100%', height:'100%'}} controls className="video-js" poster="videoposter.jpg"/>
      </div>
    )
  }
}

export default Player;

another thing to note is that this works locally when i run npm start, but when I push it to heroku, I get the Uncaught SyntaxError: Unexpected token {.
Also, this error is showing in some blob file on heroku that I have no idea where it is coming from.
I'm pretty noob at this stuff and I am trying to learn but this has me stumped. Be patient with me and let me know if I need to clarify more things. Thanks

**Comment by gesinger** [comment]
If it works locally, then that leads me to believe it has something to do with the config for production deployment, or how heroku is setup for it. I know that some people have had trouble and success in https://github.com/videojs/videojs-contrib-hls/issues/600 with issues around packaging videojs-contrib-hls with webpack, so maybe something in there may help. Otherwise I'd recommend looking to webpack or heroku support. Since this works locally, and doesn't seem to be an issue with videojs-contrib-hls, I'm going to close the issue here, as it can be hard for us to debug the config and functionality of other modules and systems. If you do happen to find an answer, please let us know in this issue or the associated webpack issue, as it might help someone searching in the future. Thanks!

**Comment by thecotne** [comment]
this is problem with `webworkify-webpack-dropin` not playing well with uglify js 

see https://github.com/videojs/videojs-contrib-hls/issues/600#issuecomment-293550845
