### ISSUE TITLE
Safari does not support currentTime(t) call for VOD

### ISSUE THREAD

**Issue by askaliuk** [videojs/videojs-contrib-hls#1087]
## Description
Safari always starts HLS VOD playlist from time 0. It does not react to currentTime(t) call. Chrome and FF work fine.

## Sources
https://playertest.longtailvideo.com/adaptive/captions/playlist.m3u8

## Steps to reproduce
1. Open https://www.w3schools.com/code/tryit.asp?filename=FEMYPED8LEAT in Safari
2. Click "Set time and play" button. Observe that playback starts from 0
3. Open https://www.w3schools.com/code/tryit.asp?filename=FEMYPED8LEAT in Chrome or FF
4. Click "Set time and play" button. Observe that playback starts from 100 seconds.

### Expected
Safari should start playback from provided time like other browsers

### Error output
None

### videojs-contrib-hls version
videojs-contrib-hls 5.4.1

### videojs version
video.js 5.18.4

### Browsers
Safari Version 10.0.3 (11602.4.8.0.1)

### Platforms
OSX El Capitan 10.11.6

### Other Plugins
No other plugins

### Other JavaScript
No other JS

**Comment by gkatsev** [comment]
On Safari, contrib-hls is disabled by default in lieu of the native playback capabilities. (You can [overrideNative](https://github.com/videojs/videojs-contrib-hls#overridenative) if you want.)
For the best support, I would recommend waiting at least for `loadedmetadata` if not `canplay` before trying to set the `currentTime`. The problem is that Safari is still loading the video when you call `currentTime` and thus it is basically ignored.

Hope that helps.

**Comment by askaliuk** [comment]
Thank you for clarification
