### ISSUE TITLE
Audio/video off sync in ad stitched live stream

### ISSUE THREAD

**Issue by lemonwhale** [videojs/videojs-contrib-hls#1090]
## Description
https://github.com/videojs/video.js/issues/4292

## Sources
https://github.com/videojs/video.js/issues/4292

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.
2.
3.

### Expected
Please describe what you expected to happen that did not happen in the description.

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls x.y.z

### videojs version
what version of videojs does this occur with?
video.js x.y.z

### Browsers
what browsers are affected? please include browser and version for each
*

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gkatsev** [comment]
From https://github.com/videojs/video.js/issues/4292

--------------

## Description
When playing a server side ad stitched stream, the video/audio gets off sync after a ad break or two. The theory is that this might be caused by discontinuity. 

video url:
http://csm-e.cds1.yospace.com/csm/live/122906630.m3u8

## Steps to reproduce
1. Play the video url in videojs player in chrome.
2. Wait for at least one ad break
3. When the content starts again, check the sync between audio and video 

## Results
### Expected
the video/audio is synced

### Actual
the video/audio is not synced (roughly 2-3 seconds)

### Error output
No console error. 

## Additional Information
No additional information

### versions
#### videojs
    "video.js": "^5.19.0",
    "videojs-contrib-hls": "^5.3.3"
#### browsers
Chrome
#### OSes
Apple desktop
### plugins
No additional plugins

**Comment by gesinger** [comment]
Sorry this ticket has gone a while without much attention. We've made a lot of changes to videojs-contrib-hls in the meantime, and I see that the stream is down. If this is still an issue with an active stream and the latest version of videojs-contrib-hls, please let us know. Thank you.
