### ISSUE TITLE
Akamai HLS file fails to load in iOS Safari

### ISSUE THREAD

**Issue by stoicbuddha** [videojs/videojs-contrib-hls#1091]
## Description
When attempting to play an m3u8 file that is encrypted via Akamai, the video file fails to load at all (gives no status, 403, etc) and attempts to reload ad infinitum.

## Sources
Public facing staging player with issue: http://staging.player.dotstudiopro.com/share/5873e2bc99f815963d9e45ae?targetelm=.player&companykey=57fe8fe399f815e309dbc2f4&loopplayback=false&autostart=true&muteonstart=false&enablesharing=true&skin=0000ff&channelid=56b8eabd97f815600d5209a6&pagetype=channel

## Steps to reproduce

1. Connect an iPhone to a Mac Laptop
2. Open the developer window for your iPhone in Safari.
3. Go to the link above and load the player via an iPhone.

### Expected
Video should play

### Error output
(CODE:3 MEDIA_ERR_DECODE)
The media playback was aborted due to a corruption problem or because the media used features your browser did not support.

## Additional Information
This project uses requireJS, and the m3u8 file is playing fine in iOS Safari by itself.

### videojs-contrib-hls version
videojs-contrib-hls 3.1.0

### videojs version
video.js 5.10.4

### Browsers
Safari 10.2.1

### Platforms
iOS 10.2.1

### Other Plugins
There are many different plugins; listing them here would be a bit much.

**Comment by gesinger** [comment]
Hey @stoicbuddha , there seems to be a lot going on on that page, making it hard to try to trace down the problem. In particular, since iOS Safari uses a native player, it's either iOS Safari's native player being unable to play that source, or some configuration that is not being run because the native player is being used/iOS functioning differently. Would you be able to create a reduced test case using our [starter template](http://jsbin.com/vokipos/8/edit?html,output) that just has an m3u8 exhibiting the problem? Thanks.

**Comment by stoicbuddha** [comment]
I'll try to put something together tomorrow.  If I can't get to it, it'll have to wait until the 1st.

**Comment by gesinger** [comment]
Hey @stoicbuddha , are you still having trouble with your stream?

**Comment by stoicbuddha** [comment]
Yes, but I've been unable to put something together yet due to various outside demands.  I'll reopen once I'm able to put something together for you to look at.
