### ISSUE TITLE
React create webapp for WebOs LG and Samsung Tizen using video hls

### ISSUE THREAD

**Issue by hungsama** [videojs/videojs-contrib-hls#1129]
I'm using for React create webapp for WebOs LG an Samsung Tizen.
I had been run build on chrome and firefox browser, it's OK !
However, when run on webOs and Tizen will appear error : 
"VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. 
MediaError"
Please, help me !

This code here: 
----------------------------------------------------------------------------------------------------------------
import React from 'react'
import video from 'videojs-contrib-hls';
import videojs from "video.js";
window.videojs = videojs;

class PlayerStream extends React.Component {

  componentDidMount() {
   let player = videojs("really-cool-video", {
    html5: {
      hls: {
        withCredentials: false
      }
    }
   });

   player.src({
     src: "http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8",
     type: 'application/x-mpegURL'
   });
    player.play();
  }
  render() {
    return <div style={{color:"red"}}>
```
    <video id="really-cool-video" controls>
    </video>
```
    </div>
  }
}
export default PlayerStream

**Comment by gesinger** [comment]
Hey @hungsama , I don't have a webOS TV to test on, but checking online it looks like they may support native HLS playback. In videojs-contrib-hls we will default to native playback if it is supported, otherwise fall back to using media source extensions (a browser feature). While webOS TV may support native playback, in our code we check by using: https://github.com/videojs/videojs-contrib-hls/blob/master/src/videojs-contrib-hls.js#L254 . Would you be able to run that code on a device and say if any of the canPlayType calls return "maybe" or "probably?" It's possible it is not returning either of those for any of the types, and is trying to fall back to media source extensions (which the browser may or may not support, and if the browser doesn't support it, videojs-contrib-hls won't have any more options for playback).

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue, please re-open the issue and let us know what the result of running that code is. Thank you.

**Comment by jayarjo** [comment]
They got their own player in Tizen to play HLS content: http://developer.samsung.com/tv/develop/guides/multimedia/media-playback/using-avplay.
