### ISSUE TITLE
HLS Stream with mp4.csmil/master.m3u8 extension doesn't play in iPad Safari

### ISSUE THREAD

**Issue by SharathEK** [videojs/videojs-contrib-hls#1184]
I have used videojs 6.2.0 and videojs-contrib-hls 5.7.0 to play an Akamai Transcoded HLS video which is in mp4.csmil/master.m3u8 format. The same video plays fine in desktop browsers (IE, FF & Chrome) but doesn't play in iPad Safari.

Getting the below error on the player -
"The media playback was aborted due to a corruption problem or because the media used features your browser did not support." - Error code 3.

Does Video JS supports only m3u8 format in iPad Safari and not mp4.csmil/master.m3u8?

Can you please help?

**Comment by mister-ben** [comment]
On iOS the device native HLS playback is used rather than videojs-contrib-hls.

mp4.csmil/master.m3u8 isn't a different format; it's regular HLS output from Akamai's re-packaging. iOS doesn't have a problem in general playing content from Akamai, this issue is most likely specific to the encoding of your particular video(s).

**Comment by gesinger** [comment]
Thanks for answering @mister-ben ! As @mister-ben said, if it plays back on desktop browsers but has trouble somewhere a native player is used (e.g., iPad Safari or Safari on desktop), it is most likely a problem with the stream or the native player. It may also be worth giving it a try in desktop Safari, where we use the native player.
