### ISSUE TITLE
BeforeRequest is properly working on IOS devices?

### ISSUE THREAD

**Issue by 39ro** [videojs/videojs-contrib-hls#1216]
### Description

The beforeRequest that I send to attach the headers is not working on IOS devices.
The video is a .m3u8 format.

On IOS Devices (iPhone, iPad...):
- Videos _with the check_ (beforeRequest - header 'token' is required) are not played.
- Videos _with no check_ (beforeRequest - header 'token' is not required) are played.

I am using the global videojs.Hls.
 
```
  videojs.Hls.xhr.beforeRequest = function (options) {
      options.headers = options || {};
      options.headers['token'] = localStorage.getItem('token');
  }
```

I tested it in other devices and different browsers and looks to works fine.

I saw that Safari needs to overrideNative support, to be able to send a beforeRequest.
```
    videojs.options.hls.overrideNative = true;
    videojs.options.html5.nativeAudioTracks = false;
    videojs.options.html5.nativeVideoTracks = false;
```

Is something required for IOS devices?

### Expected
Send the requested headers when beforeRequest is called on IOS devices.

### Error output
The only error displayed is: 
`VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. `

### videojs-contrib-hls version
    "videojs-contrib-hls": "^5.8.2",

### videojs version
    "video.js": "^6.2.4",

### Browsers - Platform
    IOS devices (Safari, Chrome - Firefox)

### Other Plugins
    "videojs-playlist": "^4.0.0"

### Other JavaScript
    Angular

**Comment by gesinger** [comment]
Hey @39ro , thanks for reporting the issue. This is due to the fact that we use native playback when on Safari (both desktop and mobile). Because native playback is used, we don't have the same feature set on Safari as on other browsers.

You are right that `overrideNative` should help this case, however, we have a known issue that using `overrideNative` for Safari causes other problems: https://github.com/videojs/videojs-contrib-hls/issues/1005

Once https://github.com/videojs/videojs-contrib-hls/issues/1005 is solved `beforeRequest` should work in combination with `overrideNative`. Closing this ticket for now in favor of the other issue.
