### ISSUE TITLE
HLS vod playback issue

### ISSUE THREAD

**Issue by IBD** [videojs/videojs-contrib-hls#1238]
I created HLS vod from an mp4 file using ffmpeg. The video at link's provided below freezes at 19th seconds and jumps to 34th seconds on Firefox/Chrome Mac OSX 10.12.6/Windows 10. While it's playing fine on Safari Mac OSX 10.12.6. It seems like HLS playback problem for non-native HLS player.

http://13.76.248.99/videojs.html

**Comment by ariel-devsar** [comment]
Could it be maybe because your ts file is not right encoded?
I am just guessing but if you check the media info you can see that video is 3 seconds and audio 16s in the second ts file.  first TS file is like 16sseconds video + 3 seconds for this one and then there is no video.
$ mediainfo playlist21.ts -v
General
ID                                       : 1 (0x1)
Complete name                            : playlist21.ts
Format                                   : MPEG-TS
File size                                : 523 KiB
Duration                                 : 2s 533ms
Overall bit rate mode                    : Variable
Overall bit rate                         : 692 Kbps

Video
ID                                       : 256 (0x100)
Menu ID                                  : 1 (0x1)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : 27
Duration                                 : 2s 734ms
Width                                    : 800 pixels
Height                                   : 600 pixels
Display aspect ratio                     : 4:3
Frame rate                               : 15.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive

Audio
ID                                       : 257 (0x101)
Menu ID                                  : 1 (0x1)
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format version                           : Version 4
Format profile                           : LC
Muxing mode                              : ADTS
Codec ID                                 : 15
Duration                                 : 16s 623ms
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 KHz
Frame rate                               : 43.066 fps (1024 spf)
Compression mode                         : Lossy
Delay relative to video                  : -128ms
Language                                 : English

Any one knows about if there is a gap to big without video between ts files the player freeze?

**Comment by mjneil** [comment]
If there is a large gap in video or audio, the player cannot play over it. That is why you are seeing the jump to 34 seconds, the `PlaybackWatcher` detects a gap in the content and sets a timer to skip past the gap after the gap's duration

**Comment by IBD** [comment]
Hi,

The file was recorded over network. I guess there's a drop frames in the encoder side. There you see video stream shorter than audio stream.
Even though this is the case, the player should continue to play the audio stream. Spinning loading should not appear on the player.

**Comment by gesinger** [comment]
Hey @IBD , if the stream has both audio and video, then the browser expects there to be both, and, except for cases of buffer underflow (small gaps), won't resume playback of just one stream until it has buffered enough of both. This is to prevent the browser from skipping content that is simply pending download. Closing for now, as this is expected behavior. Please let us know if anything else comes up. Thank you.
