### ISSUE TITLE
cuechange event not being triggered on audio only HLS streams

### ISSUE THREAD

**Issue by nomayonnaise** [videojs/videojs-contrib-hls#1255]
## Description
The cuechange eventListener is **not** being triggered for audio only HLS streams when using this plug-in. The audio only stream contains 3 10 second .ts segments with AAC audio 64kb/s. This happens with a real live HLS stream as well.

Here are 2 examples with 3 ts segments

With audio only - cuechange event **is not** triggered
http://jsfiddle.net/8f05vyb2/

With video and audio - cuechange event **is** triggered
http://jsfiddle.net/p228339u/4/

## Sources
With audio only
http://li720-23.members.linode.com/hls/audio.m3u8
With video and audio
http://li720-23.members.linode.com/hls/video.m3u8

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Open audio only link in Chrome
2. Play video (should autoplay)

### Expected
cuechange triggered, input value is updated

### Error output
There is no error output, cuechange event not triggered.

## Additional Information
This only happens with audio only .ts segments. .ts segments with video and audio work correctly. This example only has 3 10 seconds .ts segments so the player will stop after 30 seconds.

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 5.10.1

### videojs version
what version of videojs does this occur with?
video.js 6.2.8

### Browsers
what browsers are affected? please include browser and version for each

Google Chrome 60.0.3112.113

### Platforms
what platforms are affected? please include operating system and version or device and version for each

Windows 7,8.1,10, OSX/MacOs

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.

None

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.

None

**Comment by mjneil** [comment]
Looks like metadata cues are not being added to the track in an audio only case. Comment in contrib-media-sources 
https://github.com/videojs/videojs-contrib-media-sources/blob/master/src/virtual-source-buffer.js#L516
`// TODO: are video tracks the only ones with text tracks?` I guess this answers that question

**Comment by nomayonnaise** [comment]
Thanks @mjneil for pointing me in the right direction.

**Comment by uraspaz88** [comment]
I don't think the merge has been done yet but I can confirm that the issue is still present. I'm using videojs-6.8.0, and videojs-contrib-hls-5.14.1. Something I noticed in my cross-browser/device testing was that Safari on OSX/iOS does fire the cuechange event with audio-only HLS streams, possibly due to Apple's native HLS support, but other browsers/devices fail to fire the cuechange event for audio-only HLS streams.

Related, the native HLS support built into Edge and Android seems to have an issue where the addtrack event doesn't fire when the initial ID3 info is received. In this case, using the hls.overrideNative option is a decent work-around. I'm a github noob, so if I can provide other info, let me know.

**Comment by jamesjieye** [comment]
@uraspaz88, the pull request is still open https://github.com/videojs/videojs-contrib-media-sources/pull/172.

The current workaround is to change the library in `node_modules` directly which is not ideal.
