### ISSUE TITLE
Error on Nokia lumia 535 on UC Browser 

### ISSUE THREAD

**Issue by samueleastdev** [videojs/videojs-contrib-hls#1256]
## Description
We have been made aware that a user is having an issue with playback on their nokia lumia 535 on UC Browser 

Example for testing here.

https://codepen.io/s3bubble/full/qPEZKg/

### Error output
the media could not be loaded, either because the server or network failed or because format is not supported

### videojs-contrib-hls version
videojs-contrib-hls 5.10.1 (tested with other versions aswell)

### videojs version
video.js 5.20.2 (tested with other versions aswell)

The issue seems to be specific to the UC Browser we are having no other issues from other browsers

### Browsers
Windows UC Browser 

The issue can be recreated through Chrome dev tools if you add device (Nokia Lumia 520) and visit the link https://codepen.io/s3bubble/full/qPEZKg but it is also happening on the device we understand dev tools doesn't always give a clear representation of the actual device.

Also, it is only happening for Adaptive Bitrate HLS progressive mp4's run without issues.

The error response is from this call video.js
~~~
 // middlewareSource is the source after it has been changed by middleware
    setSource(this, sources[0], function (middlewareSource, mws) {
      _this6.middleware_ = mws;
      var err = _this6.src_(middlewareSource);
     // returns an error on nokia

~~~

Thanks

**Comment by forbesjo** [comment]
Currently the player will show a source not supported error, this is because the user agent for the Nokia Lumia 520 (`Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.0; Trident/6.0; IEMobile/10.0; ARM; Touch; NOKIA; Lumia 520)`) indicates that it's IE10 which we have dropped support for. Due to the decreasing support for Windows phones we may not consider fixing this issue.

Please let us know if this support is still desired and we'll consider it for the VHS project (the next major version of videojs-contrib-hls)
