### ISSUE TITLE
Player se queda en "loading"

### ISSUE THREAD

**Issue by luchoweb** [videojs/videojs-contrib-hls#1264]
## Description
Estoy usando el player pero cuando por cuestiones de velocidad este queda cargando un .TS el player al terminar de cargarse ese TS no lo reproduce de inmediato, sino que se queda en "loading" como hasta el tercer TS vuelve y arranca.

**Comment by gesinger** [comment]
Hey @luchoweb , if I'm understanding correctly, the player does not start playing until 3 segments have loaded. It could be due to short segment durations, but do you happen to have a sample stream, and would you be able to use our [starter template](http://jsbin.com/vokipos/8/edit?html,output) to create a reduced test case? Thank you.

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls, please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.
