### ISSUE TITLE
Question: how to fallback to dash when hls is not supported

### ISSUE THREAD

**Issue by ahmadawada11** [videojs/videojs-contrib-hls#1270]
I am using the videojs-contrib-hls and videojs-contrib-dash plugins, 

I need to fallback to dash if the browser unable to play hls. i placed the links in src(hls,dash), but it is not working. i tired it on firefox version 43.0. 

if flash is installed and the tech order flash then html the player will play the hls.

**Comment by mjneil** [comment]
Is the issue that when providing an HLS and DASH source and HLS is not supported, the player falls back to playing HLS with flash instead of first trying the DASH source? This could be be fixed by having html come first in the tech order.

Or is the issue that when providing an HLS and DASH source, HLS is not supported, and flash is NOT installed, the player fails with the HLS source and does not ever try the DASH source?

**Comment by ahmadawada11** [comment]
yes  the issue that when providing an HLS and DASH source, HLS is not supported, and flash is NOT installed, the player fails with the HLS source and does not ever try the DASH

in the console i see this error

InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable in contrib-hls

**Comment by forbesjo** [comment]
Could you share a jsbin of your code for debugging?

**Comment by blacksail29** [comment]
hi guys,

trying the same fallback from hls to dash without success. Dash fails on android , my live streams get latency with dash. All is pefect with hls ....
is there a sense to do that ? perhaps i have to choise from hls to dash ?

thanks for help,

eric

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls, please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.
