### ISSUE TITLE
不能使用require的方式引入??  想用webpack打包发现报错

### ISSUE THREAD

**Issue by pollux2015** [videojs/videojs-contrib-hls#1276]
## Description
不能使用require的方式引入??  想用webpack打包发现
![image](https://user-images.githubusercontent.com/11935278/31435540-77f5a448-ae45-11e7-9e4d-ed2f5d53465c.png)
![image](https://user-images.githubusercontent.com/11935278/31435559-8a255cf8-ae45-11e7-8372-f9d5f0240a27.png)

**Comment by gkatsev** [comment]
If I understand the google translate correctly, you're trying to use this project with webpack and it isn't working. Unfortunately, there are some issues with this due to how we built this project.
There's a lot of discussion and work-arounds in #600. Unfortunately, refactoring the project to provide support for webpack without configuration changes has proven non-trivial.
