### ISSUE TITLE
Set custom referer and useragent

### ISSUE THREAD

**Issue by alex2844** [videojs/videojs-contrib-hls#1317]
Hello.

Please add the ability to change "referer" and "useragent".

Thank you.

**Comment by Timsonrobl** [comment]
@alex2844 assuming you are talking about adding custom headers to XHR requests - it is impossible due to security limitations hard-coded in all modern browsers.
You can see forbidden headers [here](https://chromium.googlesource.com/chromium/blink.git/+/99b8c9800ac123eddc3e199088d22569c5294b22/Source/core/xml/XMLHttpRequest.cpp#85).

**Comment by gesinger** [comment]
For cases that are allowed by the browser, we have https://github.com/videojs/videojs-contrib-hls#hlsxhr . For cases disallowed by the native `XMLHttpRequest`, we don't currently have more control.

**Comment by gesinger** [comment]
And thanks @Timsonrobl !
