### ISSUE TITLE
VideoJS Contrib HLS - Live Stream M3U8 - Pause follow with Play return to Direct

### ISSUE THREAD

**Issue by niccout** [videojs/videojs-contrib-hls#1324]
## Description
I use videoJS v6.6.0 with contrib hls v5.12.2.
The live stream display correctly, but when I hit "Pause", and waite around 10 secondes, if i click Play again the video restard but it return to Live. The video will not resume a the same position when i hit Pause.

## Steps to reproduce
1. Start a live stream
2. Hit Pause
3. Wait 10 secondes
4- Hit Play
5- The vidéo doesn't restard at the same position. It restart at LIVE position.

I need your help because it was ok with videojs 4.10

**Comment by gesinger** [comment]
Hey @niccout , if your manifest is short (shorter than 10 seconds in your example), then this is expected behavior. Otherwise, we should resume from where the video was paused. Are you still seeing this behavior, and would you be able to provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)? Thank you.

**Comment by gesinger** [comment]
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls, please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.
