### ISSUE TITLE
overrideNative is not honoured when the videojs player is 

### ISSUE THREAD

**Issue by harshil93** [videojs/videojs-contrib-hls#1339]
## Description
The following code doesn't use contrib-hls on Edge, Chrome Mobile etc where HLS native support is available even when override options are provided. The culprit here is the setTimeout. If we remove setTimeout, contrib-hls is used and we get the `window.player.tech_.hls` object otherwise it is undefined.
```
<html>
<head>
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/video.js/6.6.2/alt/video-js-cdn.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/6.6.3/video.js"></script>
        <script src="videojs-contrib-hls.js"></script>
</head>

<link href="http://vjs.zencdn.net/6.6.3/video-js.css" rel="stylesheet">

<body>
        
        <script>
                videojs.options.hls.overrideNative = true;
                videojs.options.html5.nativeAudioTracks = false;
                videojs.options.html5.nativeVideoTracks = false;
                
                
        </script>
        
        <video id="example-video" width=600 height=300 class="video-js vjs-default-skin" preload="none"  controls>
                <source id="vid"
                src="https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8"
                type="application/x-mpegURL">
        </video>
        <script>
                setTimeout(() => {
                        window.player = videojs('example-video');   
                }, 0);                 
        </script>
</body>
</html>
```

### Expected
window.player.tech_.hls should be supported.

### Browsers
Edge, Chrome mobile

**Comment by mjneil** [comment]
I think this is because with the `setTimeout` it gives the browser a chance to handle the source natively before videojs can intervene. If you need the `setTimeout`, I suggest either setting the source with the player api `player.src()` instead of using the `<source>` element. Another option could be to use the `<video-js>` embed element instead of `<video>`. That should allow you to use `<source>` element without the browser handling it natively.

**Comment by gkatsev** [comment]
Some more information: this happens because of Video.js's handling for "late init". If the video has already loaded, Video.js tries to just go with it instead of selecting another tech and source handler. We probably would want to add some kind of option to Video.js to force it to go through source selection even in late-init case.

**Comment by gesinger** [comment]
@gkatsev , should this be moved over as a possible enhancement issue in video.js' repo?

**Comment by gkatsev** [comment]
probably something that might be worth to add for v7 with VHS in by default. But we should probably also be recommending the `<video-js>` embed since it gets around the "late init" issue.

**Comment by gesinger** [comment]
Thanks @gkatsev . Closing over here (in videojs-contrib-hls) then, as that sounds like a good solution.
