### ISSUE TITLE
More complete "Getting Started"

### ISSUE THREAD

**Issue by sblandford** [videojs/videojs-contrib-hls#167]
The "Getting Started" requires some expansion to show _all_ the HTML and JS required to play
1) An HLS encoded video as local files
2) A live HLS stream from a streaming server

**Comment by Tralapo** [comment]
This issue has been silent since December last year, but I would like to support this. I don't want to be negative, I just want to explain how difficult I find it to use this tech so you guys, who know this stuff very well, can use this to make it easier for people to understand.

In my opinion, "Getting started" should, just like over at the main video.js, be enough to actually get started. Over here, it isn't. I did develop a few websites over the years and I do use video.js with success, so I do have some coding experience and feeling, but I've never ever once got this tech working.

At the moment, the Getting Started is suggesting that, next to the video.js files (can those be CDN hosted, like video.js advices in their Getting Started?), you just add:

```
<script src="videojs-media-sources.js"></script>
<script src="videojs-hls.min.js"></script>
```
Which is not the case. It won't work. You just get 'No compatible source found'. By the way, videojs-hls.min.js isn't even available to download, so you have to change it to videojs-hls.js, which is a bad first impression.

But, as said, it just won't work (for a HLS live stream that is). So, confused as you are, you open 'example.html'. Where you find a lot of files included. And I really mean a lot. Should I include all of them too? Why aren't they mentioned in the Getting Started? I don't know. Some of them use node_modules, but are traceable to media-sources or video.js itself, so that's fine and I can find those files over there. But this? What is this?

```
<script src="node_modules/pkcs7/dist/pkcs7.unpad.js"></script>
```
I don't know. Do I need it? Where do I have to get it? It's just confusing.

In the release blog for Video.js 5.0, they speak very enthusiastic about the 1.0 version of contrib-hls coming up soon. Video.js itself can be very easily deployed, even by people who almost never code. Especially because of the fact contrib-hls is now named in the 5.0 release blog, it should be more noob-proof. It would be a shame if all the hard work is for nothing, because people can't get it to work.

**Comment by forbesjo** [comment]
It looks like the dist folder is missing from npm/the latest github tag which should include the combined videojs-hls.js file and the minified version. The getting started section also does not direct users to use the files in the dist folder or how to build it locally using grunt. I also agree that this plugin should be on a CDN if it would help people get set up faster.

**Comment by Tralapo** [comment]
@forbesjk You appear to be right, the /dist folder is just missing. That explains why the files found in the repo don't work and the Getting Started is confusing.

**Comment by ingen0s** [comment]
the /dist folder is not missing - you just have to build it

**Comment by Tralapo** [comment]
Offcourse. But if you want your project to be easy to deploy for everyone (like Video.js itself is!) it should be included, because not everyone is able to build it.

**Comment by forbesjo** [comment]
Getting started and the deploy process are updated to handle this problem
