### ISSUE TITLE
Support Audio Only track in plugin

### ISSUE THREAD

**Issue by paytonrules** [videojs/videojs-contrib-hls#22]
The issue listed below has not been fixed in the videojs master branch or the feature branch for HLS.  I'm re-creating it here because the apple settings require the audio only track, but this breaks the Chrome / Flash fallback.  I'm hoping it's already fixed, and apologize if so but github removed the messaging functionality.

https://github.com/videojs/video.js/issues/813

**Comment by forbesjo** [comment]
This currently works in master if your video starts with the audio only rendition then switches up, this will not work with the new multiple audio track feature work because we are creating both audio and video source buffers early and browsers don't allow for switching source buffers after the fact. We might fix this in the future if the browsers start behaving.
