### ISSUE TITLE
Video.js: buffered unavailable on Hls playback technology element

### ISSUE THREAD

**Issue by jezhodges** [videojs/videojs-contrib-hls#235]
Experiencing this problem with the Flash fallback. Any ideas?

**Comment by dmlap** [comment]
Are you sure you have Flash installed on your test machine? It's not installed by default on the VMs from modern.ie, and this issue sounds like a symptom of missing Flash.

**Comment by jezhodges** [comment]
Yes it is installed. I get about 1 second of the audio before it crashes with the following error: 

VIDEOJS: Video.js: buffered unavailable on Hls playback technology element. TypeError: undefined is not a function {stack: (...), message: "undefined is not a function"}
player.js:7929 Uncaught TypeError: undefined is not a function

The error occurs at line 7929 of videojs which is:

vjs.Flash.prototype.buffered = function(){
  return vjs.createTimeRange(0, this.el_.vjs_getProperty('buffered'));
};

The part of the script causing the crash is: "this.el_.vjs_getProperty('buffered')"

**Comment by jezhodges** [comment]
Should also mentions this only happens in Opera browsers and not in Chrome or Firefox. Any ideas?

**Comment by jezhodges** [comment]
The error happens in the video.js file with the message, "Uncaught TypeError: this.el_.vjs_getProperty is not a function". This only happens in the Opera browser.

**Comment by patriziomunzi** [comment]
I've got the same problem in chrome.
It's a blocking issue for me. I don't think the question tag is appropriate for this.
Any feedback?

**Comment by jezhodges** [comment]
My problem goes away in Chrome on a refresh. But this problem appears on first page load. It's not a case of Flash being blocked as I can see it on the page and functioning correctly through the API. However, this is a blocking issue in Opera and my player will not work. Firefox seems to be fine and I now wonder if it's an issue with media sources.

**Comment by patriziomunzi** [comment]
I haven't tried on opera yet, but in chrome in my case does not work.
I cannot understand why it's browser based.
@jezhodges A strange thing I see is that the swf get loaded twice.
Do you have the same double loading?

![screen shot 2015-06-17 at 13 18 24](https://cloud.githubusercontent.com/assets/1443016/8205718/5eca8f94-14f3-11e5-9976-b5f760950327.png)

**Comment by dmlap** [comment]
Would either of you be able to put together an example on [jsbin](http://jsbin.com/axedog/edit?html,output) or similar where we can see this occurring? This doesn't happen for me with Chrome on our [example page](http://videojs.github.io/videojs-contrib-hls/), so we need a bit more context to debug.

**Comment by jezhodges** [comment]
Yeah I can confirm that the SWF gets loaded twice by the browser. It's worth noting that this problem (certainly for me) only happens when using only the API JS.

**Comment by patriziomunzi** [comment]
You can find a html page showing the problem here: http://beta.hypertvx.com/videojs_test.html
I ran some additional tests an I noticed that the problem arises only when there are more than one source (which is not the case of your example).
The problem does not show off all the time but if you don't see it, keep reloading and it will happen.

Attached a screenshot of the problem.

![screen shot 2015-06-18 at 13 45 14](https://cloud.githubusercontent.com/assets/1443016/8230491/028a98a4-15c1-11e5-9c82-d9bfc1d1dc8d.png)

**Comment by patriziomunzi** [comment]
@dmlap have you had the chance to look at it? It's a blocking issue for me.
Thanks

**Comment by dmlap** [comment]
@patriziomunzi would it be hard to try this out with the unminified version of video.js? I think you might be hitting a variable name-mangling issue.

**Comment by redmacs** [comment]
hi @dmlap I work with @patriziomunzi, here you can find the same page with dev version of videojs: http://beta.hypertvx.com/videojs_test_dev.html
We've got the same issue also with dev version.

**Comment by jezhodges** [comment]
@dmlap @redmacs Any update on this issue?

**Comment by redmacs** [comment]
Not on our side @jezhodges, we're waiting for @dmlap !

**Comment by dmlap** [comment]
It looks like in your example video.js's time tracking interval is firing before the SWF has been initialized and that's causing an error. It's a bit surprising we don't see this more often but it's hard to predict with race conditions. This technically is an issue with the base playback tech class in video.js so I've filed https://github.com/videojs/video.js/issues/2288 over in the main repo to track it.

**Comment by redmacs** [comment]
Thanks @dmlap ! Actually it seems that the SWF is downloaded two times. Right after the second load, videojs time tracking interval fails.

**Comment by jezhodges** [comment]
Indeed. The changes @dmlap made still do not solve the problem for me. The SWF is also being downloaded twice on my page.

**Comment by samward1985** [comment]
Having the same issue with the swf loading twice (only in Chrome, strangely enough). I only have one video source.

@redmacs @jezhodges you ever find a fix?

**Comment by samward1985** [comment]
@redmacs @jezhodges @patriziomunzi @dmlap  

I figured it out! I found that the error was due to the SWF being loaded twice in Chrome, which caused some synchronization issues between the JS and SWF. I started digging around trying to find any reason the SWF might be loaded twice, and I came across the following:

  // IE6 seems to have an issue where it won't initialize the swf object after injecting it.
  // This is a dumb fix
  var newObj = par.childNodes[0];
  setTimeout(function(){
    newObj.style.display = 'block';
  }, 1000);

For whatever reason, this causes Chrome to reload the SWF. If IE6 isn't important to you (and it shouldn't be!), just comment this block out, and you're good to go. Otherwise, some browser detection would clean this right up. HTH! Please let me know if a 4.x fix gets merged!

**Comment by redmacs** [comment]
Hi @samward1985 , unfortunately we didn't use SWF anymore, so I didn't found any fix.

**Comment by forbesjo** [comment]
Is this still an issue for anyone in the thread?
