### ISSUE TITLE
Live playlist isn't starting to play until at least 2 playlists have been downloaded

### ISSUE THREAD

**Issue by shaharmor** [videojs/videojs-contrib-hls#306]
Hi,

On a live playlist, either using autoplay or by clicking play, the player doesn't start to download/play the segments until a second playlist is downloaded.

This is obviously bad as it can take as much as 10 seconds to get the next playlist and the player looks to be stuck while waiting.

To reproduce:
Go to the example page: http://videojs.github.io/videojs-contrib-hls/

Then change the source to a live playlist by running the following snippet in the console:
```javascript
player.src([{
    type: 'application/x-mpegURL',
    src: 'https://livestream.peer5.com/video/surf-drone/index.m3u8'
}]);
```

then click play and see that the player is waiting for a second playlist before starting to play (You can check the network pane)

**Comment by dmlap** [comment]
We don't begin loading segments until you actually begin playback for live videos since the "live point" is continuously moving and we don't want to waste the viewer's bandwidth. I added a call to play() immediately following your snippet and the behavior looked correct to me:

![screen shot 2015-06-15 at 10 41 32 am](https://cloud.githubusercontent.com/assets/56667/8162516/ca9ab3f6-134b-11e5-8f49-bb8ac393994a.png)

Note fileSequence3.ts (from the bipbop video) is immediately followed by index.m3u8 and then the segments of the live stream.

**Comment by shaharmor** [comment]
You right that adding a .play() will start playing immidiatly, but that is not the issue.

I used the snippet in the first post just to change the source.

consider this: If you have a page with a live url, once you click the play button it waits to download another manifest file, even if it just downloaded the last one a second ago.

So i'm mimicing it by changing the source and then manually clicking play

**Comment by dmlap** [comment]
Sorry if I misunderstood. Actually, do you think you're seeing the issue described in https://github.com/dmlap/videojs-contrib-hls/commit/1e641871380f88ddb210c5f3dca2858360cbd482?

**Comment by shaharmor** [comment]
Possible.. i'm not really into all the internals of stuff, but i just know that the playback doesn't start until another manifest file is downloaded after you click the play button.
Btw, waiting for another manifest file is fine, as long as the request for that manifest file is being made immediately after a user clicks the play button. (Today it waits the default time)

**Comment by shaharmor** [comment]
Just checked and it indeed fixes the issue.

**Comment by dmlap** [comment]
Awesome. Thanks for checking!
