### ISSUE TITLE
Loading indicator stuck in when playback

### ISSUE THREAD

**Issue by scramatte** [videojs/videojs-contrib-hls#340]
When I playback HLS live stream, the loading indicator stuck in when playback.
Please see attached capture.

![image](https://cloud.githubusercontent.com/assets/188766/8552410/25e68ea4-24dd-11e5-8e1a-81b64a3fda2f.png)

**Comment by dmlap** [comment]
Do you have an example of this we could check out?

**Comment by scramatte** [comment]
http://iptv.nicos.es/hlsbug/
It occurs mainly when switch channels

**Comment by dmlap** [comment]
@scramatte looks like you're not using the latest version of contrib-hls. Are you able to try with the latest release?

**Comment by scramatte** [comment]
Do you mean  master branch  ?

**Comment by seamug** [comment]
@scramatte is your problem solved cos I'm having the same issue

**Comment by trungpham** [comment]
i'm having the same issue too.

**Comment by gesinger** [comment]
I know this hasn't been updated in a while, but many changes have been made since its report. Are you still experiencing this issue (I noticed that the link is now down)? If so, would you be able to include a [reduced test case](https://css-tricks.com/reduced-test-cases/). There's a [starter template](http://jsbin.com/liwecukasi/edit?html,output) on JSBin you can use. Thanks!
