### ISSUE TITLE
Re-write over hls.js

### ISSUE THREAD

**Issue by Ivshti** [videojs/videojs-contrib-hls#416]
[dailymotion/hls.js](http://github.com/dailymotion/hls.js) is pretty impressive, it manages to play HLS flawlessly in html5 video through the MediaSource API. It doesn't have a large performance penalty, it's just changing the container of the segments on the fly in a webworker.

I think this is preferable to a adobe flash-based solution.

Any chance of seeing it implemented?

**Comment by gkatsev** [comment]
Hello,
hls.js is pretty cool. We've been working for a while on making this project use MSE internally for playback when possible and fall back to flash in other cases. You can see where we are now in the development branch of this repo. Also, you can track updates on this issue #382 since we are also updating contrib-hls with videojs 5.0 support at the same time.
Thanks!

**Comment by Ivshti** [comment]
Cool, thank you @gkatsev
