### ISSUE TITLE
1.0.1-0 gets stuck on the same segment

### ISSUE THREAD

**Issue by Pablo76** [videojs/videojs-contrib-hls#425]
I guess it was obvious, but I still figured it was a good idea to leave a note about it.
development (current 1.0.1-0 release) seems to be completely broken.
For example:
http://test.kolontsov.com/~/index.html

uses current release of vjs5+hls contrib, just start playback and seek to the middle of the clip. After a few fragments you'll get something like this:
http://i.imgur.com/nDfJsvb.png

playback get stuck and one fragment is endlessly re-downloaded.

**Comment by gkatsev** [comment]
The 1.0.1-0 is a prerelease. It partly works but we're working on it.

**Comment by Pablo76** [comment]
ok, regarding HLS and html5 playback. Is it supported by older release?

**Comment by Pablo76** [comment]
With latest release reported issue seems to be fixed. However, it seems that worse problems are there now.
Instead of cycling the same clip I got it cycling on my playlist now, with minor "bug" in cycling algorithm: it restarts downloading hls segments from second one: http://i.imgur.com/3NDn121.png

another issue: encrypted videos that used to play do not play anymore.
Can you lease recommend what version of hls-contrib should be used for html5-hls?
thanks

**Comment by dmlap** [comment]
Unfortunately, we're not going to be able to support video that only has a keyframe on the first segment. The HTML5 APIs that allow us to play back HLS are pretty picky and need at least one keyframe every segment to work. In fact, it's a good practice to make sure that your segments lead with a keyframe-- otherwise we may have to download multiple segments to be able to do a quality switch and that could lead to temporary playback stalls. The 0.17.x releases of this project are currently more stable but they do not support HTML-based HLS playback.

**Comment by Pablo76** [comment]
These segments use intra-frame refresh, which is effectively the same as key-frame, except that they do not have IDR nal_type. The other issue is that sps/pps are only at the beginning of each stream, and according to HLS spec, this is valid.
