### ISSUE TITLE
How to debug code 3 - MEDIA_ERR_DECODE

### ISSUE THREAD

**Issue by ntadej** [videojs/videojs-contrib-hls#447]
I'm following videojs-contrib-hls development of MSE support. We have mainly problems with live streams. They do not work at all (some worked last week at one point). Also, all my PRs from master branch were closed recently and I want to rebase them on develop.

I always get error code 3: The media playback was aborted due to a corruption problem or because the media used features your browser did not support. How to debug this error.

**Comment by dmlap** [comment]
Debugging decode errors is a bit tricky right now since the browser tech is so young. In Chrome, you can visit `chrome://media-internals/` in your URL bar to bring up a specialized [debugging console](https://www.chromium.org/audio-video/media-internals) that can help point out the problem. If the log events on that page are unclear, you can try the debugging workbench in our TS to MP4 [transmuxing project](https://github.com/videojs/mux.js). To use the workbench, clone mux.js and open [debug/index.html](https://github.com/videojs/mux.js/blob/master/debug/index.html) in your web browser. That page has instructions on one technique for identifying problems and provides probably too much info on the results of converting your TS file.

**Comment by gesinger** [comment]
Hey @ntadej , are you still encountering the error? If so, would you be able to include a [reduced test case](https://css-tricks.com/reduced-test-cases/)? There's a [starter template](http://jsbin.com/liwecukasi/edit?html,output) on JSBin you can use. Thanks!

**Comment by ntadej** [comment]
There was an issue with Chrome I think where it didn't properly detect HE vs LC AAC. It works now with latest version. There are still other issues with our streams though ;)
