### ISSUE TITLE
Stops to play after change to audio-only format (?)

### ISSUE THREAD

**Issue by norlin** [videojs/videojs-contrib-hls#486]
I have found a bug with HLS quality streams change for Live streams.
versions: vjs 5.4.4 + contrib-hls 1.2.2 (also reproducible with previous versions, at least down to vjs 5.0.2 + hls 1.0.0)

Here is an example: http://output.jsbin.com/yodozisubi/1
How to reproduce: 
in Chrome Dev Tools turn on "Network throttling" (Toggle Device Mode, Ctrl+Shift+M)
1. Run video on default good network
2. change Throttling to "Regular 2G"
3. wait for HLS download 160audio.m3u8 playlist
4. that's it, video stops and doesn't play even if turn off throttling

**Comment by dmlap** [comment]
Your stream looks geo-blocked to me but I think I know what's going on-- it's probably because of a limitation in how Media Sources behave in the browser. Basically, if we start the stream and claim there will be video, the video element stall waiting for video when you switch to an audio only stream. We have logic built in that will avoid audio-only variants to get around this problem as long as you've specified the codecs for each of your variants in your master m3u8. We'd love to do a better job with this scenario but so far the best idea we've come up with is trying to insert no-op video frames into the stream dynamically, and that's pretty complicated. 

Closing this one for now but feel free to continue the discussion in the comments if you have other suggestions.
