### ISSUE TITLE
Certain live streams are stuck after a few seconds

### ISSUE THREAD

**Issue by shacharz** [videojs/videojs-contrib-hls#491]
http://wowza.peer5.com/live/smil:clock.smil/playlist.m3u8
http://wowza.peer5.com/live/smil:nature.smil/playlist.m3u8

**Comment by Tralapo** [comment]
#483

**Comment by campones** [comment]
same for me.

I setup a low bitrate tv live stream, and on chrome, it stop after 5 6 segments. (using last chrome)

Curiously I tried on an old xperia from 2012 running android 4.0.4 and it plays perfectly..  Which is kind surprising for me to see something running smooth on mobile and not on my desktop.

Waiting for further development on this because I think this is highly interesting (getting rid of flash player)

**Comment by cowanmax** [comment]
Have the same problem but it stops after 10-15 segments.. Hope to fix it very soon. BTW with VOD is works very well. So it problem only for LIVE streams.

**Comment by raj2569** [comment]
Have the same problem here, using chrome. Version 47.0.2526.106 (64-bit) in Debian Jessie. The chrome inspector network diagnosis is attached. Let me know if any information/help is needed from my side to nail this issue.
![hls-player](https://cloud.githubusercontent.com/assets/30658/12070346/8fd39e40-b094-11e5-969f-091986cfd5a0.png)

**Comment by dobri-dobrev** [comment]
Same happens for me. As far as my debugging could show, the this.tech_.currentTime() randomly returns a time significantly earlier than the current time causing the player to crash. The currentTime increases sequentially until it seemingly randomly jumps way back and the player stops loading new segments.

I could only track the issue down to src/videojs-hls.js fillBuffer(). Hope this helps. It is unfortunately a significant blocker for us

**Comment by bobgle** [comment]
Latest working version is 1.2.2. Can you confirm try that version and report back @dobri-dobrev?

**Comment by Tralapo** [comment]
The last version I have absolutely no problems with (even in use on a live site) is 1.2.0, with 1.2.2 I ran into #460. In the versions after that this issue and #483 appeared... 
```/*! videojs-contrib-hls - v1.2.0 - 2015-11-21```

**Comment by dobri-dobrev** [comment]
@bobgle still having issues with 1.2.2
I run videojs 5.3.0 (also tried 5.4.4)
and videojs-contrib-media-sources-2.4.3

**Comment by Tralapo** [comment]
@imbcmdth @dmlap Problem still there in 1.3.5.

**Comment by bernhardreisenberger** [comment]
can confirm, that the problem still exists in 1.3.5 with video.js 5.6.0

videojs-contrib-hls - v1.2.2 is working for me

**Comment by isabo** [comment]
With video.js v5.4.x and videojs-contrib-hls v1.2.0 it doesn't work for me on Chrome. The only way I got it to work was to force it to use Flash, in which case I get a low quality video, but it's better than nothing.

**Comment by hybrisCole** [comment]
Same here, using videojs 5.6, videojs-media-sources 2.4.5 and 1.3.7, tried to downgrade to 1.2.1 but remains the same

**Comment by Tralapo** [comment]
Try this one, 1.2.0, works for me: https://gist.github.com/Tralapo/9f2b789b6c5ca28994e4

**Comment by hybrisCole** [comment]
@Tralapo it works for like 10 seconds, then it will say:

VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. MediaError {code: 3, message: "The media playback was aborted due to a corruption…media used features your browser did not support."}code: 3message: "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."__proto__: MediaError_logType @ video.js:19117log.error @ video.js:19068error @ video.js:11619handleTechError_ @ video.js:10424ret @ video.js:18946ret @ video.js:18946data.dispatcher @ video.js:18594

**Comment by hybrisCole** [comment]
I got this working using the following:

VideoJS: 5.2
videojs-contrib-media-sources : 2.4.5
videojs-contrib-hls : 1.2.1

BUT, when I dispose my videoJS Reference, I got this:

DOMException: Failed to execute 'abort' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.(…)
index.js:60 DOMException: Failed to execute 'abort' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.(…)


Wrapping the dispose() around a try catch made the trick for me.

**Comment by Tralapo** [comment]
@hybrisCole Shame it doesn't work for you. I use the 1.2.0 in my gist for I while now on my website without problems. 

I do not use videojs-contrib-media-sources by the way. There's no need to include that.

**Comment by hybrisCole** [comment]
@Tralapo yeah I read somewhere that it's not needed, but for some reason it won't detect my video format :S hehe

**Comment by Tralapo** [comment]
Did a new build just now, after reading #552 and reading his comment about .min working and indeed the problem seems to be finally fixed?! My streams keep playing now @dmlap 

Both minified and non-minified by the way, can't reproduce the problem reported in #552.

**Comment by bernhardreisenberger** [comment]
v2.0.0 non-/minified version: no issues in chrome. in firefox however, it stuck after 10min-30min.
v1.3.7 non-/minified version: playback stuck after a few seconds

**Comment by gak2** [comment]
I'm struggling with this issue: live HLS stream from Wowza freezes after 10 seconds.  I have tried all videojs/hls combinations outlined above, all to no avail. On Chrome and Firefox, the media blocks run into a loop:

media_w1438989202_52.ts media_w1438989202_53.ts media_w1438989202_54.ts media_w1438989202_53.ts media_w1438989202_54.ts media_w1438989202_53.ts

After 10secs this fails and the browser endlessly requests the same media_xxxxxx.ts chunklist. Result: the video stops dead in Chrome and Firefox goes.  It _does_ play on IE though, where it's alternately loading .m3u8, .ts, .m3u8, .ts, 

Anyone got any ideas?

Thanks!

**Comment by alonfixler** [comment]
Hi,

Did someone manage to fix this issue with the current version of videojs-contrib-hls?

Alon

**Comment by gak2** [comment]
I abandoned it Alon.  Couldn't make it work.

**Comment by gesinger** [comment]
Sorry this ticket has gone a long time without much attention. We've made a lot of changes to videojs-contrib-hls in the meantime, and the original posted streams seem to play with the latest version of videojs-contrib-hls (v4.1.1). Please give it a shot and let us know if you're still seeing issues. Thank you.

**Comment by sreym** [comment]
This bug can be reproduced for the video:
http://mahoaobj.b5695cde.cdnviet.com/tuandn/videojs/hls/vtv5-high.m3u8"

Versions: videojs 5.11.0, videojs-contrib-hls 4.1.1

**Comment by ghaydarov** [comment]
I am having the same issue with latest versions of videojs and videojs-contrib-hls on all browsers except safari. Any ideas how to fix this?

**Comment by ssanth** [comment]
I am facing the same issue as well on live streams
videojs 5.15.1
contrib hls v4.1.1
Mainly on chrome.

Would like to reopen this issue and looking for a fix.

**Comment by ghaydarov** [comment]
Here is how I got rid of this issue. I setup is on aws. I transcode videos with elastic transcoder, and I used cloud front to serve them. 
Initially I was using hlsv4 with encryption and I had this problem, video not playing after 5-10 seconds. Now I switched to hlsv3 and everything is working nicely. 
I hope this helps.

**Comment by vpowers** [comment]
I'm also seeing this on live streams. Seems to be mainly chrome for me as well although I haven't done enough testing in other browsers.

videojs 5.16.0
contrib hls 4.1.1

**Comment by erald** [comment]
Am using it for VOD with the latest releases.
Am offering multiple streams
src type rtmp,
src type hls
scr type mp4
scr type webm

I see in Chrome this result in 
<video id="player_html5_api" class="vjs-tech" preload="auto" autoplay="" src="blob:https://cdn.example.com/a5ad372e-50ca-4088-8431-536f9102ff6e">

am expecting to see the videofile in the src. The video never starts and in Firefox it gives invalid source.
of course if I change the order (first type mp4 then type has) most browsers play without problems the type mp4. have to test it with iPhone and iPad if they pick up the xls stream instead of the mp4 stream
