### ISSUE TITLE
No Audio on Chrome but its HTML5

### ISSUE THREAD

**Issue by fzakaria** [videojs/videojs-contrib-hls#506]
I am using videojs HLS plugin (thanks for the plugin) however I cannot seem to get audio to play on Chrome.

What's odd is that I'm surprised its even playing the video at all given that I've not included the SWF fallback. So there seems to be some sort of undocumented support for HLS in Chrome ?

Here is a sample URL : http://getslinger.elasticbeanstalk.com/sling/2567

**Comment by maysale01** [comment]
+1 I'm having a similar issue, but only on certain manifests. I haven't narrowed it down yet.
For the sake of discussion, we're both using `videojs v5.4.6` and `videojs-contrib-hls v1.3.3`.

**Comment by maysale01** [comment]
See this pull request: [387](https://github.com/videojs/videojs-contrib-hls/pull/387).

Both of our manifests use media groups.

**Comment by dmlap** [comment]
@fzakaria your page is currently working because you've specified an mp4 fallback source. Chrome doesn't know how to play back HLS natively so it automatically tries the mp4 URL. Audio seemed to be working on my setup but if it was failing, it's a Chrome-MP4 issue, not this project. I think the issue might be that video.js is initializing your player before HLS is loaded. You may want to try removing the data-setup attribute and using `videojs(videoElem)` once the HLS has loaded instead.

@maysale01 thanks for the example manifest. Parsing media groups is still a work-in-progress. I'm going to close this issue since it seems to be a misconfiguration but feel free to comment on #387.
