### ISSUE TITLE
Uncaught TypeError: videojs.Hls.PlaylistLoader is not a function

### ISSUE THREAD

**Issue by lime-green** [videojs/videojs-contrib-hls#512]
I'm getting the above error (Uncaught TypeError: videojs.Hls.PlaylistLoader is not a function). 

I'm using Bower and script versions: 
"video.js": "~5.5.1",
"videojs-contrib-hls": "~1.3.4",
"videojs-contrib-media-sources": "~2.4.3"

Then I load the scripts in the order: video.js -> media-sources -> HLS

What might be the problem? Thanks :)

**Comment by jhumbug** [comment]
I'm getting this as well.  My versions through npm:

"video.js": "^5.5.1",
"videojs-contrib-hls": "^1.3.4",
"videojs-contrib-media-sources": "^2.4.3",

**Comment by maysale01** [comment]
@lime-green I found that this issue was because I was using assuming that `src/videojs-hls.js` was the proper entrypoint for the plugin. 

You need to build the dist version and use `dist/videojs-hls.js`. If you're using npm to install the package from git (thanks to https://github.com/npm/npm/issues/3055), you'll need to manually run `cd node_modules/videojs-contrib-hls && npm install` (which will fail since the tests are in the `.npmignore` file). Then run `grunt build`. 

This should be remedied, as the npm package version is growing out of date with the github release version.

**Comment by gesinger** [comment]
Sorry this ticket has gone a long time without much attention, and thank you for the update @maysale01 . We now publish the npm package along with github release to ensure that both reflect the latest version.
