### ISSUE TITLE
Sample m3u8 won't play in Chrome but plays in IE/Edge/FF and does not appear to be a codec issue

### ISSUE THREAD

**Issue by raylau1234** [videojs/videojs-contrib-hls#562]
This is a playlist I snipped out of a larger video. It plays in Firefox, IE, Edge on Windows but not in Chrome on Windows. Chrome reports that "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."

http://livetools.ramp.com/FileResource/HLSMulticastChecker/ramptv/item.m3u8

However, the same video plays with hls.js (i.e. if I input the above URL into http://dailymotion.github.io/hls.js/demo/). This tends to indicate that it is not an underlying codec/Chrome issue but something in the way videojs-contrib-hls is doing the transmux.

The H.264 is the constrained baseline profile (though I think I've seen other videos in that profile play fine in Chrome.)

**Comment by dmlap** [comment]
Your TS segments are encoded with HE-AAC audio. Unless you provide codec information, we assume you're using the regular AAC audio codec and Chrome throws an error if you attempt to feed HE-AAC to and AAC SourceBuffer (even though [it probably shouldn't](https://bugs.chromium.org/p/chromium/issues/detail?id=534301)). If you create a very simple master m3u8 that lists a single variant and specify the CODECS attribute (i.e. `mp4a.40.5`) as part of the `#EXT-STREAM-INF` declaration, your stream should work.

**Comment by rafaelmcgs** [comment]
Hi there, Im encoding audios with HE-AAC and creating MP4 files...
To make the playlist files, im using nimble and smil, what is automatic...
I wanna force the code to read the Codec attribute "mp4a.40.5" without change playlists, because all of them are using HE-AAC...
I just wanna change the default value (AAC) to my own (HE-AAC)
Any Idea? Where I can set this in the code?
