### ISSUE TITLE
Stream not working with latest release

### ISSUE THREAD

**Issue by shacharz** [videojs/videojs-contrib-hls#589]
http://sport5_live1-lh.akamaihd.net/i/live3_0@129322/master.m3u8

tested with:
videojs: 5.8.0
videojs-contrib-hls: 2.0.0
Chrome 48, 49
OS: Windows 8.1, OSX 10.10.5

**Comment by tenacex** [comment]
I believe this is due to the browser not being able to access the playlist file at the given link. I have attached a screenshot of what happens when I try and visit the link in the browser. Typically visiting the link would download an .m3u8 playlist file. Since this isn't happening, I think we can attribute the fault to the stream, and not HLS.
![screen shot 2016-03-10 at 3 21 02 pm](https://cloud.githubusercontent.com/assets/10394694/13683293/ee294b0a-e6d3-11e5-941f-0395ff12450e.png)

**Comment by shacharz** [comment]
Oh that's no the error I was referring to, the link is probably geo blocked to Israeli ip's.

**Comment by gesinger** [comment]
@shacharz , sorry this ticket has gone a long time without much attention. We've made a lot of changes to videojs-contrib-hls in the meantime.

I gave the link a shot with the latest player and it seems to be working.

Would you be able to give the latest version (as of this comment, v4.1.1) a shot? If it's still a problem, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/edit?html,output)?

Thank you for reporting the issue.
