### ISSUE TITLE
Major Playback issues

### ISSUE THREAD

**Issue by winterfellzone** [videojs/videojs-contrib-hls#625]
Hello,
First of all, this scenario was tested on several players such as VLC and only occurs when using Video.js with HLS.
I'm playing back a Wowza HLS Stream, with a bitrate of 3.2Mbps in Google Chrome and Chunk duration of 3 seconds.
When playing the video, after a while it still "plays" but no video is actually being playedback.
When monitoring it using Chrome Deubg, i see that i keeps downloading the m3u8 chunk list with a reference for new generated ts files as needed.
The problem is that it does not download those ts files but only dispalys them in the chunk manifests.
What can i do about it?
Thank You !

**Comment by billybobilly** [comment]
related?   #650

**Comment by dmlap** [comment]
Hard to say from your description. Have you ever seen this behavior with non-live content? Any chance you have an example stream we can look at?

**Comment by billybobilly** [comment]
We don't do any non-live, so no.  I can turn on a live stream when you need it.  How can we set up a time?    Can we PM off the list so I can give you the live URL and coordinate?

**Comment by billybobilly** [comment]
I haven't solved it, but have worked around it by altering a few settings
on the encoder to limit how fast it encodes, adding to the number of
segments per manifest, and changing the buffer time in
videojs-contrib-hls.js to 60 seconds.  I left everything else
in videojs-contrib-hls.js alone. I've played the same stream on other
players an never been able to duplicate the problem.

So what I've found is that if the encoder delivers segments any faster than
about 1.2x the fps rate of playback, the buffering mechanism on the player
can't keep up and eventually skips a .ts segment which causes it to set the
duration of that segment to the last known total length and then calls that
segment  'end'.  At that point the buffer plays out and no more .ts files
are downloaded.  For example, if my encoder is encoding at a pace of 50 fps
and the target frame rate of the output .ts files is 29.97 fps, then it is
delivering .ts files at about 1.66 times faster than the player will
consume them.

I believe what's happening is that while the player is emptying it's buffer
to hit it's target buffer of 30 seconds, it takes too long and the manifest
no longer has the next .ts in the list.  That must cause the player to
loose it's place and quit. This is just a guess since I don't really know
how videojs-contrib-hls.js triggers its downloads.

That's why a combination of forcing the encoder to take it's time encoding
frames, adding to the number of .ts files there are in the manifest, and
making the videojs-contrib-hls.js buffer 60 seconds allows it to keep
going.

Unfortunately, it's not very easy to tune the encoder to hit a target of
1.2x the output framerate so I either encode too slowly and the playback
stutters waiting for the next segment, or I go too fast and overrun the
buffer and crash it.

I hope this helps.  I'm not a good .js programmer so I'm afraid I'm not
much help.  If you still want a stream to test with, I can schedule some
live streams for you over several hours one day if you tell me when you can
look at them.

Bill

**Comment by alonfixler** [comment]
Hi,

I'm suffering from the same issue. I've noticed that enlarging the buffer causes the stream to play longer without getting stuck but eventually it's stopping.
Is there any way to solve this issue? I'm dealing with many frame rates so trying to change the encoder is not something I want to do.

**Comment by billybobilly** [comment]
In the end, it turned out to be a problem with encoding.  In ffmpeg, using the -re flag in the command forces ffmpeg to encode at the sources' frame rate.  For example: " /usr/local/bin/ffmpeg -re -loglevel info . . . "

It makes sense.  You can't push more into the player than it can playback in the given time.  Eventually the buffer will overrun.

We didn't see it with live streams because a live source can't create more than a real time stream.  We only saw the problem with a pre-recorded file.  In the case of the file, ffmpeg without the extra -re flag will encode it as fast as it can and results in ffmpeg output at sometimes more than double the framerate as the playback.  Clearly, if the player can't play out everything the encoder is sending in the given buffer size, it will overrun.  The buffering can compensate for momentary surges or gaps, but not a long term net positive.

Hope this helps.

**Comment by nhollander** [comment]
@billybobilly and @alonfixler we are seeing these freezing issues when Live streaming via an Elemental encoder. We are not using a wowza config however can reproduce the same issue you have both laid out.We are trying to narrow down whether this is an encoder issue or a video.js player. Can you both confirm that your fix was on the encoders end and that video.js player can do live streaming without these issues?

**Comment by m1ch3lp3r3z** [comment]
@billybobilly, @alonfixler just to support @nhollander comment, below is an image snap from the issue actually happening. This test was performed on Chrome browser using video js player. At some point in the video the TS requests start to getting behind with respect to the range given by the m3u8. Our first guess is that those TS are becoming available faster than the player is consuming them, however the player was not showing any pauses or cuts. And the interesting part is that the player stopped calling TS when the last loaded TS (154) was not anymore among the ones in the range from the m3u8, which was already starting from 155. So this sounds similar in some way to the issue you've described that's why we think there might be contact points.

https://www.evernote.com/l/AN4ZjYdIMl5IpL88VH977hFqjG42pP_05eE

Sorry for the blurred areas, we need to keep privacy from a third party.

Thank you.

**Comment by billybobilly** [comment]
I can confirm that our final fix of adding the -re flag to ffmpeg, telling it to encode at the source video frame  rate resolved the buffer overrun. So, it was on the encoder side. This was for VOD.  Live encoding was not affected because it can only be encoded at it's original frame rate and ffmpeg can't get ahead of it. 

The way we identified that it was a buffer overrun in the first place was by adding a couple of debugging console.log() lines to the buffering section of video.js to watch the size of the buffer, what the m3u8 file list  contained, and see when it was asking for more .ts files.  That's where we saw it get behind the m3u8 list and then crash - presumably because it couldn't 'skip' a whole chunk and go to the next one.

If adding to the buffer size delays the crash for you, then I'd have to guess that it's a buffer overrun like we were having.  I haven't used Elemental encoders, so I can't help there.

**Comment by nhollander** [comment]
@billybobilly thank you for the response. I am wondering if you might be able to take look here at our player with the a live streaming running in it and see if you can replicate the issue 

http://devmobilerider.com/users/julio/test_player_20160928.html

**Comment by alonfixler** [comment]
Hi,
In the end, for many reasons I decided to go with hls.js (https://github.com/dailymotion/hls.js/tree/master) and not with videojs-contrib-hls so I can't help you on this issue.

**Comment by juliomenendez** [comment]
@alonfixler did you integrate hls.js with video.js or just went without video.js entirely?

**Comment by alonfixler** [comment]
@juliomenendez I integrated hls.js with video.js with the help of vjs-hls: A small video.js plugin that creates the connection between hls.js and video.js.
