### ISSUE TITLE
contrib hls doesn't work on chrome ver 34

### ISSUE THREAD

**Issue by winterfellzone** [videojs/videojs-contrib-hls#637]
Hi,
Video.JS by itself does support Chrome browser 3+.
I did not see any reference regarding contrib hls browser support.
Using both contrib-hls and video.js, i am able to play my HLS video stream using chrome version 43, but fail to playback using chrome 34.
Is Chrome version 34 supported?
I know that chrome version 34 supportes natively MSE.
the error i'm getting is this:
CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED
On versin 43 on another computer same environment - it works.
Regards

**Comment by winterfellzone** [comment]
Someone Please?

**Comment by samward1985** [comment]
+1 to having major issues in Chrome - FF and Safari seem fine. I'll get more specific as I experience issues.

**Comment by samward1985** [comment]
I get this a lot, seemingly randomly: VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. 

only in chrome

**Comment by vietlongn** [comment]
Same here, it's seem like videojs-contrib-hls messed up with HE-AAC codec

**Comment by dmlap** [comment]
With Chrome's auto-updating policy, we can't realistically support versions as old as 34. If you're seeing issues in newer Chrome though, please open another issue. Sorry!

**Comment by pacepace** [comment]
I'm experiencing this problem with Chrome 57.  Firefox, Safari, Edge all work fine.  On Chrome it will play the first segment and then it will fail with the "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."  If I disable the hardware acceleration in Chrome, playback continues beyond the first segment.  This problem is occurring across all the Chrome's I've tested.  Please note that all the machines I tested on have hardware accelerated graphics.  None of them are funky weird graphics, they are either higher end Nvidia cards (980s, 1080s) or they are integrated Intel. All the systems are WIndows 10.

Additionally, on the first load of the page (regardless of the hardware accel setting) on Chrome it says "No compatible source for this media" and never tries to load the m3u8.  A force-refresh on the page brings it to the point where it can play the first segment.
