### ISSUE TITLE
vidoe js contrib hls demo is not working in android firefox

### ISSUE THREAD

**Issue by nafisakanwal** [videojs/videojs-contrib-hls#649]
http://videojs.github.io/videojs-contrib-hls/
this demo page is not working in android 's firefox 

Can anyone tell, is it some support issue with vidoe js at android firefox browsers

Thanks in advance

**Comment by gkatsev** [comment]
We don't really do testing on Firefox for Android. We register the source handler with videojs after the native html5 tech, plus, firefox claims that it could possibly play back HLS (it returns "maybe" from `canPlayType`) and thus when trying to play back an m3u8, we just hand it off to firefox directly which it fails. To fix this, we'd need to check for Android and register the source handler before the native one (https://github.com/videojs/videojs-contrib-hls/blob/5a4d09f71ad22fcbb31fc3f52df4a8a1bcb87ac7/src/videojs-contrib-hls.js#L1601-L1603). But then, when our source handler is loaded, it would still end up disabling it because we think that native HLS is supported (https://github.com/videojs/videojs-contrib-hls/blob/5a4d09f71ad22fcbb31fc3f52df4a8a1bcb87ac7/src/videojs-contrib-hls.js#L1588-L1590).
Hope that helps.

**Comment by dmlap** [comment]
We're not planning on overriding native HLS behavior for Firefox on Android soon, so I'm going to close this one.
