### ISSUE TITLE
when you click on the play, but also in the load

### ISSUE THREAD

**Issue by erbing** [videojs/videojs-contrib-hls#690]
In the Android browser, when you click on the play, but also in the load, but after the end of the load, the video has been played for a few seconds to load

**Comment by gesinger** [comment]
Hey @erbing , sorry this ticket has gone a long time without much attention. By default we use Android's native HLS player, so this issue is most likely related to Android. We do provide an option to override native playback via `videojs.options.hls.overrideNative = true`. If you try that, and still see the issue, would you be able to reopen the ticket and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)? Thank you.
