### ISSUE TITLE
 Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers.

### ISSUE THREAD

**Issue by nearwmy** [videojs/videojs-contrib-hls#705]
when playing m3u8 happy this "Uncaught QuotaExceededError: Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers."

**Comment by dmlap** [comment]
What version of contrib-hls and video.js are you using? Is your stream publicly available for us to check?

**Comment by nearwmy** [comment]
use  the version 2.0.1 ,and I try to change key for 'loadSegment' ,In this function can change 'removeToTime',but not work.because our ts sheet is really big ,so maybe over the chorme's limit

**Comment by forbesjo** [comment]
Is this still an issue? If so could you post a stream?

**Comment by RichardLanham** [comment]
I think I know what the problem was, and the solution. I was getting the identical error. Identical. But I think I fixed it incidentally by doing player.dispose().

In my case, I was creating, starting, and destroying multiple video.js HLS players. I noticed in the network tab that they weren't really going away, so I looked for the proper way to get rid of them: dispose(). The ghost players went away, of course, and incidentally, I have not seen this error since then.

**Comment by tchakabam** [comment]
we had this problem with 4K streams as they are just too big, and videojs only limits by buffer time duration, but not size.

i have a fix here but it wasn't looked at yet by anyone of videojs project it seems: https://github.com/videojs/videojs-contrib-hls/pull/1242
