### ISSUE TITLE
Cannot play video stream on android simulator mode - Chrome

### ISSUE THREAD

**Issue by whatvn** [videojs/videojs-contrib-hls#742]
## Description
Playing demo page with android (Nexus 6P) on Chrome Version 51.0.2704.84 (64-bit)
, Mac OSx El Capitan, video cannot be played.

## Steps to reproduce

1. Open demo page in chrome
2. activate android simulator or responsive mode in chrome 
3. cannot play 

### Expected
Demo page should be play-able 
### Actual
Demo page cannot play in simulator mode

### Error output
> video.js:21167 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)
 The media could not be loaded, either because the server or network failed or because the format is not supported. 
MediaError {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}code: 4 message: "The media could not be loaded, either because the server or network failed or because the format is not supported."
__proto__: Object_logType @ video.js:21167log.error @ video.js:21118error @ video.js:12417handleTechError_ @ video.js:11222ret @ video.js:20996ret @ video.js:20996data.dispatcher @ video.js:20644

**Comment by gkatsev** [comment]
On Android, we don't yet run contrib-hls but let the native functionality handle HLS since most modern versions of Android support it natively -- at least to some extent. Android simulators tend to be very finicky with respect to videos so I'm going to wager that that is the issue. Playing the demo page on my physical 6P device works just fine.

**Comment by whatvn** [comment]
understood!
