### ISSUE TITLE
Audio chunk is not downloaded at all

### ISSUE THREAD

**Issue by whatvn** [videojs/videojs-contrib-hls#750]
## Description

I do not know this issue is addressed or not, I remember I did post issue about it before, but cannot find it, so I create a new one. 
Problem: with m3u8 playlist that has 2 different link for audio and video, videojs contrib hls just download video chunk, discard audio. 
## Steps to reproduce

See jsbin link: 
http://jsbin.com/qixuxawogu/edit?html,output
### Expected

Videojs-contrib-hls should download both audio and video chunks, and stream should have sound too. 
Now we have only video, no sound
### Sources

Link is included in example above.
### videojs-contrib-hls

videojs-contrib-hls 3.1.0
#### videojs

what version of videojs does this occur with?
video.js 5.10.4
#### browsers

Chrome, and maybe other browsers
*
#### Operating Systems

MacOSx

**Comment by CSilivestru** [comment]
I had a very similar experience but it turned out that I was editing my playlist files in TextEdit on MacOS X and, since Mavericks, it doesn't insert ASCII compliant quotes in your plain text documents. This was causing my playlist files to look correct but be mis-parsed.

I highly suggest you run your stream files through Apple's `mediastreamvalidator` module. Helpful video [here](https://developer.apple.com/videos/play/wwdc2016/510/)

You can download the tools at their developer download page [here](https://developer.apple.com/download/more/?=http%20live%20streaming%20tools)

Hope that helps!

**Comment by gesinger** [comment]
Hey @whatvn , sorry this ticket has gone a long time without much attention. We've made a lot of changes to videojs-contrib-hls in the meantime, and the original posted streams seem to play with audio with the latest version of videojs-contrib-hls (v5.4.0): http://jsbin.com/nojeyeqizu/1/edit?html,output

 Please give it a shot and let us know if you're still seeing issues. Thank you, and thanks @CSilivestru  for helping out with some recommendations.
