### ISSUE TITLE
Unable to switch hls alternate audio track on Android Chrome

### ISSUE THREAD

**Issue by scramatte** [videojs/videojs-contrib-hls#751]
Hi,

I'm unable to switch hls alternate audio track on Android Chrome.
Alternate audio button never appears in the player. So it's imposible to change audio track.

Regards

**Comment by gkatsev** [comment]
contrib-hls doesn't currently run on Chrome for Android. We let the native HLS functionality take over. Native Chrome for Android does not support alternate audio tracks right now.
We are thinking of making contrib-hls run on chrome for android over the native functionality but that might take a while because we'd need to test it and fix any issues.
