### ISSUE TITLE
Chrome displays incorrect CEA-608 embedded captions

### ISSUE THREAD

**Issue by ianwelsh** [videojs/videojs-contrib-hls#761]
I'm having an issue where my live stream's embedded CEA-608 captions are being displayed incorrectly in Chrome. 
They are working as expected in Firefox, but in Chrome the words have characters in incorrect places. See the image for an example. 

![screen shot 2016-06-29 at 2 29 26 pm](https://cloud.githubusercontent.com/assets/8646670/16463915/f662670a-3e05-11e6-936e-a5275a59aaba.png)

Any ideas why this is happening?

**Comment by gesinger** [comment]
Sorry this ticket has gone a long time without much attention.

It looks like this may have been due to https://github.com/videojs/mux.js/pull/112

@ianwelsh , would you be able to give the latest version a shot (as of this comment, v5.4.0), and if you are still seeing the issue, let us know the source you are seeing it with?

Thanks for reporting the issue.

**Comment by ianwelsh** [comment]
Yes, https://github.com/videojs/mux.js/pull/112 fixed it.

**Comment by gesinger** [comment]
Thanks!
