### ISSUE TITLE
Switching resolution of live stream breaks the playback

### ISSUE THREAD

**Issue by mkhazov** [videojs/videojs-contrib-hls#765]
## Steps to reproduce

1. Play video in low/med quality, e.g. 360p
2. Switch to 720p
3. Wait for a while...

### Expected
Video should play in 720p

### Actual
Video stops playing.

The same 720p .ts is being requested in a loop:
![2016 07 15 00-32-59](https://cloud.githubusercontent.com/assets/3628510/16856595/b5a1003a-4a23-11e6-9db7-e26c6d24396e.png)

### Sources
http://codepen.io/mkhazov/pen/yJprKP?editors=1010

#### videojs-contrib-hls
videojs-contrib-hls 3.1.0

#### videojs
video.js 5.10.4 - 5.10.7

#### browsers
Chrome

**Comment by sobytes** [comment]
Hi All,

Just to add to this issue i have a live problem which you can see here, it stops and also will stop when fullscreen is pressed.

http://jsbin.com/lidifunuje/1/edit?html,output

Thanks

**Comment by Boxie5** [comment]
After update contrib-hls to 4.10.0 and videojs to 5.16.0, I'm still facing this issue while #798 is not happening.

I dig into the code of contrib-hls, found that was because segment repeats downloading when timeout. This is implemented in #770 .

But this really happens frequently if our customers try to switch to a resolution which needs higher network speed. Basically, this will led to loading repeatedly forever and a lot of wasted traffic.

So, I would like to ask is it possible to set the timeout value dynamically for different repeating times. Looking forward to @mjneil 's reply, thinks a lot!
