### ISSUE TITLE
support strict base-uri CSP policies

### ISSUE THREAD

**Issue by dgoldstein0** [videojs/videojs-contrib-hls#832]
## Description

I was just trying to set a CSP policy of `base-uri: "self"` on my website which uses video.js.  I was surprised to find that even with videojs 5.10.7 (we are upgrading now), we still set a <base> tag as part of the videojs code.

I finally tracked this down to https://github.com/videojs/videojs-contrib-hls/blob/2cce0c1859a53fee5c6ed46deb79cfc550cead45/src/resolve-url.js#L15.  Which leaves me with a bunch of extra questions.

1) I don't care about IE6 support.  Heck, I don't even care about IE8 support.  Can we modernize this code?
2) I first went poking around in the videojs code and found their `parseUrl` function, which looks very similar.  Would it be possible to use this instead?  I would be a fan of anything that reduces the size of the compiled code, as it's pretty large right now.  https://github.com/videojs/video.js/blob/master/src/js/utils/url.js#L14
## Sources

Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.
https://github.com/videojs/videojs-contrib-hls/blob/2cce0c1859a53fee5c6ed46deb79cfc550cead45/src/resolve-url.js#L15
## Steps to reproduce

Explain in detail the exact steps necessary to reproduce the issue.
1.  use videojs 5.10.7 with videojs-contrib-hls 3.4.0.  To be precise, we've set up a project built with browserify with the following entrypoint:

```
var videojs = require('video.js');
require('videojs-contrib-hls');
module.exports = { videojs: videojs };
```

which helps us avoid the fact that videojs-contrib-hls doesn't ship as a UMD module (we load AMD).
1. set a Content-Security-Policy: base-uri: "self" on the base page, which loads the video player
2. use the resulting videojs package to play back an hls video where the playlist comes from the same domain as the page, but the segments are from a separate domain.
## Results

video should play back happily
### Expected

video playback errors out, since it requires the <base> tag to be allowed by the CSP policy.
### Error output

If there are any errors in the console, from the player, or anywhere else please include them here:
## Additional Information

Please include any additional information necessary here. Including the following:
### videojs-contrib-hls version

what version of videojs-contrib-hls does this occur with?
3.4.0, but this bug is also on the latest master
### videojs version

what version of videojs does this occur with?
5.10.7
### Browsers

what browsers are affected? please include browser and version for each
Latest Chrome & probably also Firefox.  According to MDN other browsers don't support this bit of the content-security-policy spec.
### Platforms

what platforms are affected? please include operating system and version or device and version for each
- Probably all.  I tested Windows, but I have no reason to believe this is platform-specific.

**Comment by dmlap** [comment]
@dgoldstein0 we're using the `<base>` element because m3u8 URLs need to be resolved relative to the m3u8, not the page the player is hosted on. The standard `a.href` approach doesn't work because that calculates relative to the page the player is running on. `parseUrl()` does half the job but it would still require us to translate interesting URL features like relative paths and I've been hesitant to do that because URLs are pretty complicated when you get into the nitty-gritty.

We're open to solutions that don't use `<base>` and IE6 support isn't a requirement :) Have any suggestions?

**Comment by dgoldstein0** [comment]
What's m3u8?

**Comment by dmlap** [comment]
M3U8 is the "master inventory" for an HLS video stream. When you specify an HLS video to a player, you're actually handing it a URL to an M3U8 file. That file can specify the different bitrates available for the video or a list individual video chunks. In ugly ASCII diagram format, M3U8s form a hierarchy that kind of looks like this:

```
master.m3u8
|- low-bitrate.m3u8
|  |- low/0.ts
|  `- low/1.ts
`- high-bitrate.m3u8
   |- high/0.ts
   `- high/1.ts
```

In this example, if master.m3u8 was hosted at `https://example.com/videos/master.m3u8`, the first low-bitrate segment would be at `https://example.com/videos/low/0.ts`. The tricky part here is  when you're resolving those relative URLs (e.g. `low/0.ts`) from a player hosted at a different base path than the M3U8s. If your player was at `https://example.com/pages/example.html` and you tried using the `a.href` approach, the first low-bitrate segment would be incorrectly requested from `https://example.com/pages/low/0.ts`. The mechanism we're currently using in resolvePath can handle base paths that are different from the containing page and a whole bunch of other URL complexities since it's piggy-backing on top of the browser's native URL resolution.

**Comment by dgoldstein0** [comment]
ah, makes sense.

Would it be possible to create an `iframe`, and then put your `base` tag and `a` tag inside that iframe? I believe that way the base-uri CSP policy for the main page wouldn't apply within the iframe.

**Comment by forbesjo** [comment]
We now use a purely javascript resolver (https://github.com/tjenkinson/url-toolkit) so this should no longer be an issue

**Comment by dgoldstein0** [comment]
awesome, thanks for the fix!
