### ISSUE TITLE
Player fetches live playlist while paused

### ISSUE THREAD

**Issue by mkhazov** [videojs/videojs-contrib-hls#856]
## Description

http://jsbin.com/liqusojicu/edit?html,output

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:2162400
#EXT-X-TARGETDURATION:2
#EXTINF:1.000,
1475831365000.ts
#EXTINF:1.000,
1475831366000.ts
...
```
## Steps to reproduce
1. Open the page, do not start the playback.
2. Look at the Network panel

...or
1. Start the playback
2. Pause
3. Look at the Network panel
## Results

![2016-10-07 12 19 38](https://cloud.githubusercontent.com/assets/3628510/19185036/89a42a64-8c88-11e6-8610-7f075838dc62.png)
### Expected

Player should not fetch playlist every second while the playback is paused or not started yet (autoplay is off). These requests generate extra traffic and are useless since we're not watching the video.
### videojs-contrib-hls version

videojs-contrib-hls 3.6.0

**Comment by TylerZubke** [comment]
I have also noticed this issue.

Are you able to continue watching a live stream after pausing for more than 20 seconds or so? If I pause a live stream while watching the network tab, once it gets to the point that it is only pulling down .m3u8 files I hit play and get a loading spinner and the video never resumes playing.

**Comment by dmlap** [comment]
@TylerZubke resuming live streams paused for a long time should be fixed by https://github.com/videojs/videojs-contrib-hls/pull/899 in v3.6.8.

@mkhazov we'd like to allow users to be able to pause live streams for a short period of time and resume without forcing them to seek back to the live point and miss some content. If we don't keep reloading manifests and buffering content, there will be a gap in the buffer and those segments may have disappeared by the time we resume playback. It does mean some extra buffering could occur but that amount is limited to 30 seconds. Safari on iOS behaves similarly in my testing. I'm closing this issue since this behavior is intended but I'm happy to continue the discussion.
