### ISSUE TITLE
Cannot read property 'byteLength' of undefined error when trying to play specific M3U8 file under CHROME

### ISSUE THREAD

**Issue by smarshallsay** [videojs/videojs-contrib-hls#905]
## Description
Issue only when playing a specific video - has been fine so far on others. Have re-transcoded file multiple times, source seems fine?

## Steps to reproduce
You can try loading the M3U8 file here:
https://s3-eu-west-1.amazonaws.com/tankvideoupload/transcodes/jensentest_HLSv4.m3u8

Original video file:
https://s3-eu-west-1.amazonaws.com/tankvideoupload/jensentest.mp4

### Error output
From Chrome:
videojs-contrib-hls.min.js:5 Uncaught TypeError: Cannot read property 'byteLength' of undefined(…)

From Firefox:
TypeError: e.video.initSegment is undefined videojs-contrib-hls.min.js:5:30939
[95]</</T</<.value() videojs-contrib-hls.min.js:5
[95]</</T</<.value() videojs-contrib-hls.min.js:5
t/this.transmuxer_.onmessage() videojs-contrib-hls.min.js:5

### videojs-contrib-hls version
videojs-contrib-hls@3.6.9

### videojs version
video.js@5.12.6

### Browsers
Chrome / Firefox (Edge plays OK)

### Platforms
Only Windows 10 tested so far

**Comment by dmlap** [comment]
@smarshallsay I don't know if the way you're specifying your audio-only variant stream is valid. contrib-hls is most likely loading the audio-only variant since it avoids renditions that are significantly bigger than the player viewport and your renditions are bigger than the average web player viewport. I created an alternate master m3u8 that only included the audio-only variant and that stream failed for me immediately in Safari as well.

I think this would work if you can remove the audio group definition from your audio-only stream. That is, the last entry in your master m3u8 would look like this:

```
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=146000,CODECS="mp4a.40.2"
jensentest_HLSv4_audio_v4.m3u8
```

It's not clear to me the correct way to specify alternate audio for audio-only variants. It may be a case that isn't actually handled in the spec right now. Closing this issue but please keep commenting if I've missed anything.

**Comment by smarshallsay** [comment]
Thank you for your response.

I have tried editing the M3U8 as you specify and the audio does play but without the picture - also I receive the following errors from VideoJS
Chrome: Uncaught TypeError: Cannot read property 'filter' of undefined
Firefox: TypeError: this.activeAudioGroup(...) is undefined

I am using Amazon Elastic Transcoder to make the HLS files and in the documentation it mentions that for HLS you should split your video streams from audio to leverage the late binding audio feature of HLS. AET generates the M3U8 file for me automatically based on the inputs. 

I feel like I'm missing something but I'm not sure what it is as this technique has worked flawlessly with your plugin for every video we've uploaded so far.

Thanks for your assistance with this, I realise it may not be your 'problem' since it may well not be an issue with the plugin - I appreciate the help all the same.
