### ISSUE TITLE
m3u8 files from twitch fail to load using videojs-hls

### ISSUE THREAD

**Issue by Kasher** [videojs/videojs-contrib-hls#917]
## Description
Hey,
I've been using VideoJs and the HLS plugin for quite some time now, and I'm facing a quite strange issue. Up until a few days ago, I was able to watch twitch videos using the plugin (if I give a m3u8 file as the video's source). Unfortunately, I checked that today, and apparently none of the videos load anymore (again, I'm pretty sure that it used to work correctly).

I thought that maybe Twitch added some security measures to their m3u8 files, but if I try to load the same video using VLC player (on my computer), the video loads successfully. 

Here is an example of a VOD video (not even a live stream) that fails when I use VideoJs-HLS:
http://jsbin.com/febejemodi/1/edit?html,output
When loading this page, I get the error "The media could not be loaded, either because the server or network failed or because the format is not supported.". Again, this same file works well in VLC.

In addition, when I try to load a live stream from twitch, I get a different error - I see in the dev tools that there are plenty of network requests to m3u8 files, but not even one request to a .ts file. This is really odd, and it is harder to reproduce, since I can't provide a 24\7 live stream.
In order to reproduce this, please load this page:
https://www.twitch.tv/directory/game/Dota%202 , select a video (it doesn't really matter which one), and look at the network request that your browser makes. There is a network request for a file called "index-live.m3u8". Take this URL and put it as the source of the video, and the bug will be reproduced.
Here is an example, but the live stream might be down when you check - if it does, please use the flow I have just described in order to find a live stream:
http://jsbin.com/subocutopi/1/edit?html,output

## Sources
Source #1: https://video-edge-c67a14.lhr03.hls.ttvnw.net/transcode-x2-6f5058/dreadztv_23676741328_548467223/medium/index-live.m3u8?token=id=6833500151908592589,bid=23676741328,exp=1479402332,node=video-edge-c67a14.lhr03,nname=video-edge-c67a14.lhr03,proto=https,fmt=medium&sig=e0eb4ea023e87d0ae5879332e2c72ef77f71fe25

Souce #2: https://vod054-ttvnw.akamaized.net/472ed5089b_rhykker_23620411488_544946608/medium/index-dvr.m3u8

## Steps to reproduce
Explained earlier..

### Expected
The stream to load and play correctly.

### Error output
None in live stream, the error in VOD stream is quoted above.

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
videojs-contrib-hls 3.6.6

### videojs version
video.js 5.12.5

### Browsers
Tested only in Chrome 54.0.2840.100

### Platforms
Arch Linux, 64-bit

### Other Plugins
No, this is the only plugin.

### Other JavaScript
None.

Thanks in advance,
Roee.

**Comment by mjneil** [comment]
For the VOD source (https://vod054-ttvnw.akamaized.net/472ed5089b_rhykker_23620411488_544946608/medium/index-dvr.m3u8), the browser throws `No 'Access-Control-Allow-Origin' header is present on the requested resource.`. Twitch must've recently disabled CORS or this would probably still work. Nothing we can really do about this.

For the live, its interesting that it was working previously and not anymore. I wonder if they recently made some changes to their encoding that is causing a slight difference in timing that is causing the segment fetching logic to hang up. The good news is whats failing here is one of the many problems we've been trying to address in our current beta build. The current build is 3.7.0-beta4. you can see [here](http://jsbin.com/nevegaxeco/edit?html,output) that the live stream seems to be working with this build. Note that since its still in beta, its not completely stable, but it is close, so stay tuned.

**Comment by Kasher** [comment]
Thanks you @mjneil ,you have helped me a lot :+1: :+1: 
I will try the beta version for sure .
