### ISSUE TITLE
PlayBackrates and Default subtitles ?

### ISSUE THREAD

**Issue by surikat1978** [videojs/videojs-contrib-hls#932]
playbackrates doesn't  work if it  
data-setup="{ &quot;html5&quot;: { &quot;nativeTextTracks&quot;: false },&quot;playbackRates&quot; : [0.7, 0.8, 0.9, 1, 1.2, 1.5]}">
and  how to make the running any default subtitles?  is it possible?

**Comment by mjneil** [comment]
if `data-setup="{ "html5": { "nativeTextTracks": false },"playbackRates" : [0.7, 0.8, 0.9, 1, 1.2, 1.5]}">` is a snippet from your html code, your double quotes within the attribute are probably causing some issues. try using `data-setup='{ "html5": { "nativeTextTracks": false },"playbackRates" : [0.7, 0.8, 0.9, 1, 1.2, 1.5]}'>`. If that is not the issue, please make an issue in the [video.js project](https://github.com/videojs/video.js) since this is not an hls specific issue.

**Comment by surikat1978** [comment]
`data-setup="{ &quot;html5&quot;:`

**Comment by mjneil** [comment]
Using character entities won't work. Try using single quotes for the outer quotations or single quotes for all the quotes within the outer qoutes

```
data-setup='{ "html5": { "nativeTextTracks": false },"playbackRates" : [0.7, 0.8, 0.9, 1, 1.2, 1.5]}'
``` 
or
```
data-setup="{ 'html5': { 'nativeTextTracks': false },'playbackRates' : [0.7, 0.8, 0.9, 1, 1.2, 1.5]}"
```

**Comment by surikat1978** [comment]
not one editor does not support a single quotes.  Such as TinyMCE or FroalaEditor .. 
it is against the rules of html.
Okay! It does not matter! HLS does not support data- setup...
Never mind!
 Thanks!

**Comment by gesinger** [comment]
Hey @surikat1978 , it's hard to debug the issue without seeing it on a page. If you're still having trouble, would you be able to re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output)? Thanks.
