### ISSUE TITLE
How to add a manual quality picker for this plugin ?

### ISSUE THREAD

**Issue by elhampour** [videojs/videojs-contrib-hls#944]
I am using this plugin to handle hls streaming but i also need to add a quality picker for users to select any quality? how can i achieve this ?

**Comment by gesinger** [comment]
We're developing a plugin for that. Keep an eye on https://github.com/videojs/videojs-contrib-quality-levels and https://github.com/videojs/videojs-contrib-hls/pull/929. And let us know if you have any questions about them.

**Comment by gesinger** [comment]
Leaving open for now until the PR is merged.

**Comment by elhampour** [comment]
Tnx for your respond, but im in need a solution here, what do you suggest ?

**Comment by mkhazov** [comment]
you can try https://github.com/Go-Promo/videojs-resolution-switcher/tree/hls

**Comment by gesinger** [comment]
Thanks for the recommendation @mkhazov ! @elhampour , we actually just merged in https://github.com/videojs/videojs-contrib-hls/pull/929 and https://github.com/videojs/videojs-contrib-quality-levels is available as a plugin to make it easy to request player.qualityLevels() and enable/disable them. videojs-contrib-hls now supports it as of version 4.1.0. https://github.com/videojs/videojs-contrib-quality-levels has some documentation on how you can use the feature. Please let us know if you encounter any issues with it.

**Comment by msencenb** [comment]
Thank you for doing this, and the excellent contrib-quality-levels plugin. Today I wrote a custom UI component that exposes a little quality picker, and to turn on a specific quality I loop through the players qualityLevels and set everything except one to disabled. But it appears that it doesn't switch to the new stream until the next segment. Is there anyway to force contrib-hls to reload the current segment with the new qualitylevels set on the player, rather than waiting for the existing segment to finish?
