### ISSUE TITLE
Different behavior on Chrome and Safari

### ISSUE THREAD

**Issue by HSY229** [videojs/videojs-contrib-hls#945]
I made the playlist with below step:
1. download master playlist with http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8
2. download child playlist with http://www.streambox.fr/playlists/x36xhzz/url_0/193039199_mp4_h264_aac_hd_7.m3u8
3. download first segment and rename to `0.ts`
http://www.streambox.fr/playlists/x36xhzz/url_0/url_462/193039199_mp4_h264_aac_hd_7.ts
4. download the next segment and rename to `1.ts`
http://www.streambox.fr/playlists/x36xhzz/url_0/url_463/193039199_mp4_h264_aac_hd_7.ts
5. create playlist `out.m3u8`
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-TARGETDURATION:11
#EXTINF:10.000,
0.ts
#EXTINF:10.000,
1.ts
#EXT-X-ENDLIST
```

The `out.m3u8` is work on Safari and Chrome.
![work](https://cloud.githubusercontent.com/assets/5857510/21599546/32c2fa70-d1a9-11e6-9904-f3bbe2dde16b.jpeg)

Then I modify the playlist to below:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-TARGETDURATION:11
#EXTINF:10.000,
0.ts
#EXTINF:10.000,
0.ts
#EXTINF:10.000,
1.ts
#EXT-X-ENDLIST
```

The behavior is different in Safari and Chrome.
Safari: 
The duration is 30 seconds.
It play `0.ts` first, then play the next segment `0.ts`, then play `1.ts`.

Chrome:
It load `0.ts, 0.ts, 1.ts`.
![failed](https://cloud.githubusercontent.com/assets/5857510/21599622/96baa57c-d1aa-11e6-9230-84ed814709e2.jpg)
The duration is 20 seconds.
Then only play 2 segments, `0.ts` and `1.ts`.

But I expect `Video.js` can play 3 segments on Chrome, just same as on Safari.

**Comment by forbesjo** [comment]
This seems like an unusual use case, if you would like to break the timeline of segments you'll have to indicate this with a discontinuity tag. The reason why Chrome and Safari are behaving differently is because the native HLS playback in Safari is probably just appending the segments while the MSE playback in Chrome is overwriting the segment in the timeline position.

We believe that the Chrome behavior is preferable.
