### ISSUE TITLE
the video playing is choppy when seeked randomly

### ISSUE THREAD

**Issue by DonkeyInBeijing** [videojs/videojs-contrib-hls#960]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/liwecukasi/edit?html,output) on JSBin you can use.

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Playing a video with m3u8 file. (the code rate is under 720p with good network speed)
2. Click on the progress bar randomly.
3. I should always wait for a while before playing again.

### Expected
The video should be playing smoothly.

### Error output
ignore

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls x.y.z

### videojs version
what version of videojs does this occur with?
video.js x.y.z

### Browsers
what browsers are affected? please include browser and version for each
*

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gesinger** [comment]
Hey @DonkeyInBeijing , when you seek in a video, even with good network speed, the segment must be downloaded, transmuxed, and then appended to the buffer. And with certain HLS playlists, sometimes the first seek is not accurate due to inaccurate timing information, meaning we have to restart the process to get a new segment until we find the segment that covers the seeked to time.

If you have an example playlist that seems to be taking a while on seeks, we'd be happy to take a look and see if maybe due to stream timing issues our seeks are not optimal, the segments are large enough to be causing delays, or there are any optimizations we can make (with the stream or player). Let us know, and thanks.

**Comment by 418900516** [comment]
hi  @gesinger @DonkeyInBeijing  ,now we use the hls.js library ,found the time when the segment appended the buffer to the seeked is less than the videojs-contrib-hls library and the time reduced from the seeking to the seeked 。
the hls.js demo:
           http://dailymotion.github.io/hls.js/demo/

**Comment by gesinger** [comment]
Closing for now. I tested some sources comparing the players and saw similar performance for seeking in both. If you have a certain source that seems to perform better in one player versus the other when seeking, please let us know. Thanks!
