### ISSUE TITLE
Preroll with videojs-vast-vpaid plugin starts at end

### ISSUE THREAD

**Issue by TylerZubke** [videojs/videojs-contrib-hls#961]
## Description
We use the MailOnline videojs-vast-vpaid plugin for preroll ads and when we play a preroll at the beginning of a live video it will usually skip most, if not all, of the preroll. The cause is is in the setupFirstPlay function in master-playlist-controller (https://github.com/videojs/videojs-contrib-hls/blob/cb9c95401ac47e2c8bb1b1335ad078cbab6e632a/src/master-playlist-controller.js#L735). The line ``` this.tech_.setCurrentTime(seekable.end(0)); ``` is the reason. It is seeking to the latest position, but because there is a preroll playing it sets the currentTime to the very end of the preroll, often skipping it entirely and going straight into the live stream. On rare occasions, it will work okay because the ```!this.hasPlayed_()``` but this doesn't happen often.

## Sources
N/A

## Steps to reproduce

1. Add videojs-vast-vpaid plugin and hls plugin
2. Start a preroll before live stream

## Results

Most of the time, you will see the last half second of the preroll. Sometimes you see none of it and the player goes straight into playing the live stream

### Expected
Preroll starts from beginning and when it finishes the live stream stars from the latest media position

### Error output
N/A

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 4.0.1

### videojs version
what version of videojs does this occur with?
video.js x.y.z

### Browsers
what browsers are affected? please include browser and version for each
*Chrome and Firefox

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Mac and Windows

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*videojs-vast-vpaid

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gesinger** [comment]
Hey @TylerZubke , when a live stream is set we want to seek to the latest seekable position (so that we are at the live point). If a preroll has to play before it, it might make sense for that source to be set before the live source is set (or some other alternative). This might make more sense to be handled outside of videojs-contrib-hls, as this project should seek to the live point as soon as possible for a live source.

**Comment by gesinger** [comment]
Closing for now. Thanks for reporting @TylerZubke , but I think this should be handled outside of videojs-contrib-hls, since videojs-contrib-hls should only focus on playing HLS. However, if it turns out that videojs-contrib-hls is not firing appropriate events/handling order of operations for playback in a sane way that allows other plugins to listen and act appropriately, feel free to re-open or create a new issue here.
