### ISSUE TITLE
Playback errors for live with really slow connections

### ISSUE THREAD

**Issue by dmlap** [videojs/videojs-contrib-hls#982]
## Description
If your available bandwidth is much lower than the starting bitrate, playback may never begin. The starting segment will take up to the request timeout to complete (45 seconds by default) and by that time, you may have slipped out the back of the live window. The PlaybackWatcher will never seek you back into the live window because your original seek never completed and so you never downshift to a more appropriate variant.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Throttle bandwidth down to 50 kbps ("GPRS" in Chrome)
2. Load a page with a live stream that contains a variant around 3 Mbps and one closer to 50 kbps
3. Hit play

### Expected
Playback eventually starts and progress is made, with maybe some big buffering delays.

#### Actual
Playback might start but it quickly stops and never picks back up again.

**Comment by gesinger** [comment]
From issue https://github.com/videojs/videojs-contrib-hls/issues/491 , a live stream that may exhibit the same issue is http://mahoaobj.b5695cde.cdnviet.com/tuandn/videojs/hls/vtv5-high.m3u8 .

This stream only has 5 segments in the live window, with each around 4 seconds. Due to a slow connection, the playlist refreshes before the segment download completes, and the segment falls off the end of the playlist.

Playback eventually started when running in Safari, but I haven't managed to get playback to start in Chrome.

**Comment by gesinger** [comment]
Should be handled by https://github.com/videojs/videojs-contrib-hls/pull/1006

**Comment by gesinger** [comment]
This should be fixed as of the latest release (v5.3.2). Please give it a shot and if you are still experiencing an issue, please re-open or file a new issue. Thank you.
